import type { Exercise } from "@/lib/exercises/types";

/**
 * All exercises for all lessons.
 * Organized by lesson: l1-e1 … l16-e5
 */
export const ALL_EXERCISES: Exercise[] = [
  // ══════════════════════════════════════════════════
  // LESSON 1 – בבית הספר (At School)
  // ══════════════════════════════════════════════════
  {
    id: "l1-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "teacher",
    questionType: "word",
    options: ["מורה", "מחברת", "עיפרון", "שולחן"],
    correctIndex: 0,
    wordId: "school-02",
    difficulty: "A1",
  },
  {
    id: "l1-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "notebook",
    questionType: "word",
    options: ["ספר", "מחברת", "תיק", "עט"],
    correctIndex: 1,
    wordId: "school-07",
    difficulty: "A1",
  },
  {
    id: "l1-e3",
    type: "matching",
    instruction_he: "חברו כל מילה בעברית לתרגום שלה",
    pairs: [
      { id: "m1", english: "school", hebrew: "בית ספר", wordId: "school-01" },
      { id: "m2", english: "book", hebrew: "ספר", wordId: "school-03" },
      { id: "m3", english: "pencil", hebrew: "עיפרון", wordId: "school-04" },
      { id: "m4", english: "bag", hebrew: "תיק", wordId: "school-08" },
    ],
    difficulty: "A1",
  },
  {
    id: "l1-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I carry my books in my {{blank}}.",
    answer: "bag",
    options: ["bag", "book", "desk", "pencil"],
    wordId: "school-08",
    difficulty: "A1",
  },
  {
    id: "l1-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage:
      "This is my classroom. I have a book and a pencil on my desk. My teacher is very nice. We learn English every day.",
    question_he: "מה יש לתלמיד על השולחן?",
    options_he: ["ספר ועיפרון", "מחברת ועט", "תיק וסרגל", "לוח וספר"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 2 – המשפחה שלי (My Family)
  // ══════════════════════════════════════════════════
  {
    id: "l2-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "grandmother",
    questionType: "word",
    options: ["אמא", "דודה", "סבתא", "אחות"],
    correctIndex: 2,
    wordId: "family-05",
    difficulty: "A1",
  },
  {
    id: "l2-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "brother",
    questionType: "word",
    options: ["אח", "אחות", "בן", "דוד"],
    correctIndex: 0,
    wordId: "family-03",
    difficulty: "A1",
  },
  {
    id: "l2-e3",
    type: "matching",
    instruction_he: "חברו כל מילה בעברית לתרגום שלה",
    pairs: [
      { id: "m1", english: "mother", hebrew: "אמא", wordId: "family-01" },
      { id: "m2", english: "father", hebrew: "אבא", wordId: "family-02" },
      { id: "m3", english: "sister", hebrew: "אחות", wordId: "family-04" },
      { id: "m4", english: "baby", hebrew: "תינוק", wordId: "family-07" },
    ],
    difficulty: "A1",
  },
  {
    id: "l2-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "My {{blank}} is my father's mother.",
    answer: "grandmother",
    options: ["grandmother", "aunt", "sister", "mother"],
    wordId: "family-05",
    difficulty: "A1",
  },
  {
    id: "l2-e5",
    type: "listening",
    instruction_he: "הקשיבו ועשו עיגול על התשובה הנכונה",
    ttsText:
      "My name is Sara. I have a mother, a father, and one brother. My brother is eight years old.",
    question_he: "כמה אחים יש לשרה?",
    options_he: ["אחד", "שניים", "שלושה", "אין לה"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 3 – אוכל טעים (Tasty Food)
  // ══════════════════════════════════════════════════
  {
    id: "l3-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "apple",
    questionType: "word",
    options: ["בננה", "גזר", "תפוח", "עוגה"],
    correctIndex: 2,
    wordId: "food-01",
    difficulty: "A1",
  },
  {
    id: "l3-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "bread",
    questionType: "word",
    options: ["חלב", "לחם", "אורז", "פיצה"],
    correctIndex: 1,
    wordId: "food-02",
    difficulty: "A1",
  },
  {
    id: "l3-e3",
    type: "matching",
    instruction_he: "חברו כל מילה בעברית לתרגום שלה",
    pairs: [
      { id: "m1", english: "apple", hebrew: "תפוח", wordId: "food-01" },
      { id: "m2", english: "milk", hebrew: "חלב", wordId: "food-04" },
      { id: "m3", english: "egg", hebrew: "ביצה", wordId: "food-06" },
      { id: "m4", english: "sandwich", hebrew: "כריך", wordId: "food-07" },
    ],
    difficulty: "A1",
  },
  {
    id: "l3-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I drink orange {{blank}}.",
    answer: "juice",
    options: ["juice", "milk", "water", "banana"],
    wordId: "food-09",
    difficulty: "A1",
  },
  {
    id: "l3-e5",
    type: "listening",
    instruction_he: "הקשיבו ועשו עיגול על התשובה הנכונה",
    ttsText:
      "For lunch I eat a sandwich and drink orange juice. Then I eat an apple. My favorite food is pizza.",
    question_he: "מה האדם שותה לצהריים?",
    options_he: ["חלב", "מיץ תפוזים", "מים", "מיץ תפוח"],
    correctIndex: 1,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 4 – חיות (Animals)
  // ══════════════════════════════════════════════════
  {
    id: "l4-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "elephant",
    questionType: "word",
    options: ["אריה", "פיל", "קוף", "סוס"],
    correctIndex: 1,
    wordId: "animals-08",
    difficulty: "A1",
  },
  {
    id: "l4-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "rabbit",
    questionType: "word",
    options: ["ציפור", "דג", "ארנב", "פרה"],
    correctIndex: 2,
    wordId: "animals-05",
    difficulty: "A1",
  },
  {
    id: "l4-e3",
    type: "matching",
    instruction_he: "חברו כל מילה בעברית לתרגום שלה",
    pairs: [
      { id: "m1", english: "cat", hebrew: "חתול", wordId: "animals-01" },
      { id: "m2", english: "dog", hebrew: "כלב", wordId: "animals-02" },
      { id: "m3", english: "bird", hebrew: "ציפור", wordId: "animals-03" },
      { id: "m4", english: "fish", hebrew: "דג", wordId: "animals-04" },
    ],
    difficulty: "A1",
  },
  {
    id: "l4-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "A {{blank}} can fly.",
    answer: "bird",
    options: ["bird", "cat", "dog", "horse"],
    wordId: "animals-03",
    difficulty: "A1",
  },
  {
    id: "l4-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage:
      "I have a cat and a dog. My cat is black. My dog is big and brown. I love my animals. Every morning I give them food and water.",
    question_he: "איזה צבע החתול?",
    options_he: ["חום", "לבן", "שחור", "כתום"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 5 – מזג האוויר (Weather)
  // ══════════════════════════════════════════════════
  {
    id: "l5-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "sunny",
    questionType: "word",
    options: ["גשום", "שמשי", "מעונן", "רוחות"],
    correctIndex: 1,
    wordId: "weather-01",
    difficulty: "A1",
  },
  {
    id: "l5-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "cold",
    questionType: "word",
    options: ["חם", "שמשי", "קר", "רוחות"],
    correctIndex: 2,
    wordId: "weather-05",
    difficulty: "A1",
  },
  {
    id: "l5-e3",
    type: "matching",
    instruction_he: "חברו כל מילה בעברית לתרגום שלה",
    pairs: [
      { id: "m1", english: "hot", hebrew: "חם", wordId: "weather-04" },
      { id: "m2", english: "rainy", hebrew: "גשום", wordId: "weather-02" },
      { id: "m3", english: "cloudy", hebrew: "מעונן", wordId: "weather-03" },
      { id: "m4", english: "windy", hebrew: "רוחות", wordId: "weather-06" },
    ],
    difficulty: "A1",
  },
  {
    id: "l5-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "In winter, it is very {{blank}}.",
    answer: "cold",
    options: ["cold", "hot", "sunny", "windy"],
    wordId: "weather-05",
    difficulty: "A1",
  },
  {
    id: "l5-e5",
    type: "listening",
    instruction_he: "הקשיבו ועשו עיגול על התשובה הנכונה",
    ttsText:
      "Today is Monday. The weather is sunny and warm. It is not cold. Let us go to the park!",
    question_he: "מה יום היום בסיפור?",
    options_he: ["יום ראשון", "יום שני", "יום שלישי", "יום חמישי"],
    correctIndex: 1,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 6 – הבית שלי (My Home)
  // ══════════════════════════════════════════════════
  {
    id: "l6-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "bedroom",
    questionType: "word",
    options: ["מטבח", "חדר שינה", "חדר אמבטיה", "גינה"],
    correctIndex: 1,
    wordId: "home-04",
    difficulty: "A1",
  },
  {
    id: "l6-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "kitchen",
    questionType: "word",
    options: ["מטבח", "חדר", "ספה", "חלון"],
    correctIndex: 0,
    wordId: "home-03",
    difficulty: "A1",
  },
  {
    id: "l6-e3",
    type: "matching",
    instruction_he: "חברו כל מילה בעברית לתרגום שלה",
    pairs: [
      { id: "m1", english: "door", hebrew: "דלת", wordId: "home-05" },
      { id: "m2", english: "window", hebrew: "חלון", wordId: "home-06" },
      { id: "m3", english: "bed", hebrew: "מיטה", wordId: "home-08" },
      { id: "m4", english: "table", hebrew: "שולחן", wordId: "home-07" },
    ],
    difficulty: "A1",
  },
  {
    id: "l6-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I sleep in my {{blank}}.",
    answer: "bed",
    options: ["bed", "sofa", "kitchen", "door"],
    wordId: "home-08",
    difficulty: "A1",
  },
  {
    id: "l6-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage:
      "My house has a kitchen and three bedrooms. I have a big bed in my room. There is a table in the kitchen. We eat dinner together every evening.",
    question_he: "כמה חדרי שינה יש בבית?",
    options_he: ["אחד", "שניים", "שלושה", "ארבעה"],
    correctIndex: 2,
    difficulty: "A1",
  },
  // ══════════════════════════════════════════════════
  // LESSON 7 – מה השעה? (What Time Is It?)
  // ══════════════════════════════════════════════════
  {
    id: "l7-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "morning",
    questionType: "word",
    options: ["ערב", "בוקר", "לילה", "צהריים"],
    correctIndex: 1,
    wordId: "time-06",
    difficulty: "A1",
  },
  {
    id: "l7-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "hour",
    questionType: "word",
    options: ["דקה", "שנייה", "שעה", "יום"],
    correctIndex: 2,
    wordId: "time-16",
    difficulty: "A1",
  },
  {
    id: "l7-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "Monday", hebrew: "יום שני", wordId: "time-01" },
      { id: "m2", english: "Friday", hebrew: "יום שישי", wordId: "time-05" },
      { id: "m3", english: "morning", hebrew: "בוקר", wordId: "time-06" },
      { id: "m4", english: "evening", hebrew: "ערב", wordId: "time-08" },
    ],
    difficulty: "A1",
  },
  {
    id: "l7-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "School starts on {{blank}}.",
    answer: "Monday",
    options: ["Monday", "Saturday", "evening", "night"],
    wordId: "time-01",
    difficulty: "A1",
  },
  {
    id: "l7-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "I wake up every morning at seven o'clock. In the afternoon I eat lunch at school. In the evening my family eats dinner together. On Friday we rest and spend time together.",
    question_he: "מתי המשפחה אוכלת ארוחת ערב יחד?",
    options_he: ["בבוקר", "בצהריים", "בערב", "בלילה"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 8 – הגוף שלי (My Body)
  // ══════════════════════════════════════════════════
  {
    id: "l8-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "head",
    questionType: "word",
    options: ["יד", "ראש", "רגל", "עיין"],
    correctIndex: 1,
    wordId: "body-01",
    difficulty: "A1",
  },
  {
    id: "l8-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "leg",
    questionType: "word",
    options: ["זרוע", "כתף", "רגל", "ברך"],
    correctIndex: 2,
    wordId: "body-08",
    difficulty: "A1",
  },
  {
    id: "l8-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "eye", hebrew: "עיין", wordId: "body-03" },
      { id: "m2", english: "ear", hebrew: "אוזן", wordId: "body-04" },
      { id: "m3", english: "nose", hebrew: "אף", wordId: "body-05" },
      { id: "m4", english: "mouth", hebrew: "פה", wordId: "body-06" },
    ],
    difficulty: "A1",
  },
  {
    id: "l8-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I write with my {{blank}}.",
    answer: "hand",
    options: ["hand", "foot", "ear", "nose"],
    wordId: "body-02",
    difficulty: "A1",
  },
  {
    id: "l8-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "I have two eyes to see, two ears to hear, and a nose to smell. I have two hands and two legs. I wash my hands and face every morning.",
    question_he: "כמה ידיים יש לי?",
    options_he: ["אחת", "שתיים", "שלוש", "ארבע"],
    correctIndex: 1,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 9 – הבגדים שלי (My Clothes)
  // ══════════════════════════════════════════════════
  {
    id: "l9-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "shirt",
    questionType: "word",
    options: ["מכנסיים", "חולצה", "שמלה", "נעליים"],
    correctIndex: 1,
    wordId: "clothes-01",
    difficulty: "A1",
  },
  {
    id: "l9-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "shoes",
    questionType: "word",
    options: ["גרביים", "כובע", "נעליים", "מעיל"],
    correctIndex: 2,
    wordId: "clothes-05",
    difficulty: "A1",
  },
  {
    id: "l9-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "pants", hebrew: "מכנסיים", wordId: "clothes-02" },
      { id: "m2", english: "hat", hebrew: "כובע", wordId: "clothes-07" },
      { id: "m3", english: "coat", hebrew: "מעיל", wordId: "clothes-08" },
      { id: "m4", english: "socks", hebrew: "גרביים", wordId: "clothes-06" },
    ],
    difficulty: "A1",
  },
  {
    id: "l9-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I wear a {{blank}} when it is cold.",
    answer: "coat",
    options: ["coat", "shirt", "dress", "sandals"],
    wordId: "clothes-08",
    difficulty: "A1",
  },
  {
    id: "l9-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "Today I wear a blue shirt and black pants. On my feet I have white shoes and socks. When it is cold outside I put on my coat and hat.",
    question_he: "איזה צבע יש לחולצה?",
    options_he: ["שחורה", "לבנה", "כחולה", "אדומה"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 10 – צבעים ותיאורים (Colors & Descriptions)
  // ══════════════════════════════════════════════════
  {
    id: "l10-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "blue",
    questionType: "word",
    options: ["ירוק", "אדום", "כחול", "צהוב"],
    correctIndex: 2,
    wordId: "colors-02",
    difficulty: "A1",
  },
  {
    id: "l10-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "big",
    questionType: "word",
    options: ["קטן", "גדול", "מהיר", "איטי"],
    correctIndex: 1,
    wordId: "adj-01",
    difficulty: "A1",
  },
  {
    id: "l10-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "red", hebrew: "אדום", wordId: "colors-01" },
      { id: "m2", english: "green", hebrew: "ירוק", wordId: "colors-03" },
      { id: "m3", english: "yellow", hebrew: "צהוב", wordId: "colors-04" },
      { id: "m4", english: "small", hebrew: "קטן", wordId: "adj-02" },
    ],
    difficulty: "A1",
  },
  {
    id: "l10-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "The sky is {{blank}}.",
    answer: "blue",
    options: ["blue", "red", "green", "black"],
    wordId: "colors-02",
    difficulty: "A1",
  },
  {
    id: "l10-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "I have a big red ball. My book bag is blue and small. The grass in our garden is green. The sun is yellow and very bright.",
    question_he: "איזה צבע הכדור?",
    options_he: ["כחול", "ירוק", "אדום", "צהוב"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 11 – העיר שלי (My City)
  // ══════════════════════════════════════════════════
  {
    id: "l11-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "library",
    questionType: "word",
    options: ["מסעדה", "פארק", "ספרייה", "בית חולים"],
    correctIndex: 2,
    wordId: "places-05",
    difficulty: "A1",
  },
  {
    id: "l11-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "park",
    questionType: "word",
    options: ["פארק", "חנות", "מוזיאון", "קולנוע"],
    correctIndex: 0,
    wordId: "places-04",
    difficulty: "A1",
  },
  {
    id: "l11-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "store", hebrew: "חנות", wordId: "places-01" },
      { id: "m2", english: "restaurant", hebrew: "מסעדה", wordId: "places-06" },
      { id: "m3", english: "airport", hebrew: "שדה תעופה", wordId: "places-08" },
      { id: "m4", english: "zoo", hebrew: "גן חיות", wordId: "places-10" },
    ],
    difficulty: "A1",
  },
  {
    id: "l11-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I borrow books from the {{blank}}.",
    answer: "library",
    options: ["library", "zoo", "airport", "restaurant"],
    wordId: "places-05",
    difficulty: "A1",
  },
  {
    id: "l11-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "My city has many places. I go to the park to play. My mother shops at the store. On weekends we eat at a restaurant. I love going to the zoo to see animals.",
    question_he: "לאן הם הולכים לראות חיות?",
    options_he: ["לפארק", "לחנות", "לגן חיות", "למסעדה"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 12 – ספורט ותחביבים (Sports & Hobbies)
  // ══════════════════════════════════════════════════
  {
    id: "l12-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "basketball",
    questionType: "word",
    options: ["כדורגל", "טניס", "כדורסל", "שחייה"],
    correctIndex: 2,
    wordId: "sport-01",
    difficulty: "A1",
  },
  {
    id: "l12-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "reading",
    questionType: "word",
    options: ["ציור", "שחייה", "ריקוד", "קריאה"],
    correctIndex: 3,
    wordId: "hobby-01",
    difficulty: "A1",
  },
  {
    id: "l12-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "soccer", hebrew: "כדורגל", wordId: "sport-02" },
      { id: "m2", english: "tennis", hebrew: "טניס", wordId: "sport-03" },
      { id: "m3", english: "dancing", hebrew: "ריקוד", wordId: "hobby-10" },
      { id: "m4", english: "video games", hebrew: "משחקי מחשב", wordId: "hobby-14" },
    ],
    difficulty: "A1",
  },
  {
    id: "l12-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I play {{blank}} with my friends after school.",
    answer: "soccer",
    options: ["soccer", "reading", "painting", "sleeping"],
    wordId: "sport-02",
    difficulty: "A1",
  },
  {
    id: "l12-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "My hobbies are reading and drawing. My brother loves playing basketball and soccer. On weekends our family likes to go hiking together. My friend plays video games every evening.",
    question_he: "מה האח אוהב לעשות?",
    options_he: ["לקרוא ולצייר", "לשחק כדורסל וכדורגל", "לטייל", "לשחק משחקי מחשב"],
    correctIndex: 1,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 13 – רגשות ותכונות (Emotions & Traits)
  // ══════════════════════════════════════════════════
  {
    id: "l13-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "happy",
    questionType: "word",
    options: ["עצוב", "כועס", "שמח", "עייף"],
    correctIndex: 2,
    wordId: "adj-11",
    difficulty: "A1",
  },
  {
    id: "l13-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "excited",
    questionType: "word",
    options: ["מבולבל", "נרגש", "מאוכזב", "נבוך"],
    correctIndex: 1,
    wordId: "emo-01",
    difficulty: "A1",
  },
  {
    id: "l13-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "sad", hebrew: "עצוב", wordId: "adj-12" },
      { id: "m2", english: "tired", hebrew: "עייף", wordId: "adj-15" },
      { id: "m3", english: "nervous", hebrew: "עצבני", wordId: "emo-02" },
      { id: "m4", english: "surprised", hebrew: "מופתע", wordId: "emo-06" },
    ],
    difficulty: "A1",
  },
  {
    id: "l13-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I am {{blank}} before the big test.",
    answer: "nervous",
    options: ["nervous", "happy", "excited", "proud"],
    wordId: "emo-02",
    difficulty: "A1",
  },
  {
    id: "l13-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "Today is my birthday! I am very happy and excited. My friends will come to my party. My little brother is sad because he cannot come. My mother is proud of me.",
    question_he: "איך הדובר מרגיש ביום ההולדת שלו?",
    options_he: ["עצוב ועייף", "כועס ומבולבל", "שמח ונרגש", "נבוך ומאוכזב"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 14 – טכנולוגיה (Technology)
  // ══════════════════════════════════════════════════
  {
    id: "l14-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "computer",
    questionType: "word",
    options: ["טלפון", "מחשב", "מסך", "מקלדת"],
    correctIndex: 1,
    wordId: "tech-01",
    difficulty: "A1",
  },
  {
    id: "l14-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "internet",
    questionType: "word",
    options: ["אינטרנט", "מסך", "עכבר", "מצלמה"],
    correctIndex: 0,
    wordId: "tech-05",
    difficulty: "A1",
  },
  {
    id: "l14-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "keyboard", hebrew: "מקלדת", wordId: "tech-02" },
      { id: "m2", english: "mouse", hebrew: "עכבר", wordId: "tech-03" },
      { id: "m3", english: "screen", hebrew: "מסך", wordId: "tech-04" },
      { id: "m4", english: "internet", hebrew: "אינטרנט", wordId: "tech-05" },
    ],
    difficulty: "A1",
  },
  {
    id: "l14-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I use a {{blank}} for my homework.",
    answer: "computer",
    options: ["computer", "pencil", "keyboard", "phone"],
    wordId: "tech-01",
    difficulty: "A1",
  },
  {
    id: "l14-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "I use a computer every day at school. I type on the keyboard and click the mouse. The screen shows my work. At home I use the internet to learn new things.",
    question_he: "מה הוא משתמש בו בבית כדי ללמוד דברים חדשים?",
    options_he: ["מקלדת", "עכבר", "אינטרנט", "מסך"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 15 – טבע וסביבה (Nature & Environment)
  // ══════════════════════════════════════════════════
  {
    id: "l15-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "forest",
    questionType: "word",
    options: ["נהר", "יער", "הר", "אוקיינוס"],
    correctIndex: 1,
    wordId: "nature-01",
    difficulty: "A1",
  },
  {
    id: "l15-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "mountain",
    questionType: "word",
    options: ["אגם", "יער", "הר", "נהר"],
    correctIndex: 2,
    wordId: "nature-05",
    difficulty: "A1",
  },
  {
    id: "l15-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "ocean", hebrew: "אוקיינוס", wordId: "nature-02" },
      { id: "m2", english: "river", hebrew: "נהר", wordId: "nature-03" },
      { id: "m3", english: "lake", hebrew: "אגם", wordId: "nature-04" },
      { id: "m4", english: "mountain", hebrew: "הר", wordId: "nature-05" },
    ],
    difficulty: "A1",
  },
  {
    id: "l15-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "Fish swim in the {{blank}}.",
    answer: "river",
    options: ["river", "mountain", "forest", "desert"],
    wordId: "nature-03",
    difficulty: "A1",
  },
  {
    id: "l15-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "Nature is beautiful. There are forests with many tall trees. Rivers and lakes have fresh water and fish. The mountains are very high. The ocean is deep and full of animals.",
    question_he: "מה יש בנהרות ובאגמים?",
    options_he: ["עצים גבוהים", "מים מתוקים ודגים", "בעלי חיים", "הרים גבוהים"],
    correctIndex: 1,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 16 – נסיעות וקניות (Travel & Shopping)
  // ══════════════════════════════════════════════════
  {
    id: "l16-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "hotel",
    questionType: "word",
    options: ["מסעדה", "מלון", "חנות", "מוזיאון"],
    correctIndex: 1,
    wordId: "travel-05",
    difficulty: "A1",
  },
  {
    id: "l16-e2",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "price",
    questionType: "word",
    options: ["הנחה", "מחיר", "קבלה", "ארנק"],
    correctIndex: 1,
    wordId: "shop-03",
    difficulty: "A1",
  },
  {
    id: "l16-e3",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "passport", hebrew: "דרכון", wordId: "travel-03" },
      { id: "m2", english: "suitcase", hebrew: "מזוודה", wordId: "travel-04" },
      { id: "m3", english: "store", hebrew: "חנות", wordId: "shop-01" },
      { id: "m4", english: "cheap", hebrew: "זול", wordId: "shop-05" },
    ],
    difficulty: "A1",
  },
  {
    id: "l16-e4",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "We sleep at a {{blank}} when we travel.",
    answer: "hotel",
    options: ["hotel", "store", "park", "school"],
    wordId: "travel-05",
    difficulty: "A1",
  },
  {
    id: "l16-e5",
    type: "reading",
    instruction_he: "קראו את הקטע וענו על השאלה",
    passage: "We went on vacation last summer. We packed our suitcases and took the airplane. We stayed at a hotel near the beach. Every day we went to the store to buy food. The prices were cheap and the food was delicious.",
    question_he: "איפה הם ישנו בחופשה?",
    options_he: ["בבית", "בפארק", "במלון", "בחנות"],
    correctIndex: 2,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 17 – ספורט ופעילות גופנית (Sports and Exercise)
  // ══════════════════════════════════════════════════
  {
    id: "l17-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "football",
    questionType: "word",
    options: ["כדורגל", "כדורסל", "כדורעף", "טניס"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l17-e2",
    type: "multiple-choice",
    instruction_he: "איזה ספורט משתמש במחבט?",
    question: "Which sport uses a racket?",
    questionType: "sentence",
    options: ["טניס", "כדורגל", "שחייה", "קפיצה"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l17-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I play {{blank}} in the park.",
    answer: "football",
    options: ["football", "tennis", "swimming", "basketball"],
    hint_he: "ספורט עם כדור גדול",
    difficulty: "A1",
  },
  {
    id: "l17-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "basketball", hebrew: "כדורסל" },
      { id: "m2", english: "swimming", hebrew: "שחייה" },
      { id: "m3", english: "tennis", hebrew: "טניס" },
      { id: "m4", english: "running", hebrew: "ריצה" },
    ],
    difficulty: "A1",
  },
  {
    id: "l17-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "team",
    questionType: "word",
    options: ["קבוצה", "אימון", "שופט", "מגרש"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 18 – עולם הטכנולוגיה (The World of Technology)
  // ══════════════════════════════════════════════════
  {
    id: "l18-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "computer",
    questionType: "word",
    options: ["מחשב", "טלפון", "טלוויזיה", "רדיו"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l18-e2",
    type: "multiple-choice",
    instruction_he: "מה משתמשים בו להקלדה?",
    question: "What do you use to type?",
    questionType: "sentence",
    options: ["מקלדת", "מסך", "עכבר", "מדפסת"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l18-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I use my {{blank}} to call my friend.",
    answer: "phone",
    options: ["phone", "computer", "keyboard", "screen"],
    hint_he: "מכשיר תקשורת",
    difficulty: "A1",
  },
  {
    id: "l18-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "internet", hebrew: "אינטרנט" },
      { id: "m2", english: "email", hebrew: "אימייל" },
      { id: "m3", english: "password", hebrew: "סיסמה" },
      { id: "m4", english: "screen", hebrew: "מסך" },
    ],
    difficulty: "A1",
  },
  {
    id: "l18-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "download",
    questionType: "word",
    options: ["הורדה", "העלאה", "שמירה", "מחיקה"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 19 – רגשות ותחושות (Feelings and Emotions)
  // ══════════════════════════════════════════════════
  {
    id: "l19-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "happy",
    questionType: "word",
    options: ["שמח", "עצוב", "כועס", "מפחד"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l19-e2",
    type: "multiple-choice",
    instruction_he: "איזו מילה פירושה כועס?",
    question: "Which word means 'angry'?",
    questionType: "sentence",
    options: ["כועס", "שמח", "עייף", "בודד"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l19-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "She is {{blank}} because she lost her toy.",
    answer: "sad",
    options: ["sad", "happy", "excited", "proud"],
    hint_he: "ההפך משמח",
    difficulty: "A1",
  },
  {
    id: "l19-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "excited", hebrew: "נרגש" },
      { id: "m2", english: "scared", hebrew: "מפחד" },
      { id: "m3", english: "proud", hebrew: "גאה" },
      { id: "m4", english: "lonely", hebrew: "בודד" },
    ],
    difficulty: "A1",
  },
  {
    id: "l19-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "nervous",
    questionType: "word",
    options: ["עצבני", "שמח", "עייף", "נרגש"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 20 – מקצועות ועבודות (Jobs and Professions)
  // ══════════════════════════════════════════════════
  {
    id: "l20-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "doctor",
    questionType: "word",
    options: ["רופא", "מורה", "שוטר", "טייס"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l20-e2",
    type: "multiple-choice",
    instruction_he: "מי מלמד בבית הספר?",
    question: "Who teaches at school?",
    questionType: "sentence",
    options: ["מורה", "רופא", "שף", "עורך דין"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l20-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "My father is a {{blank}}. He fixes cars.",
    answer: "mechanic",
    options: ["mechanic", "doctor", "teacher", "pilot"],
    hint_he: "עובד עם מכוניות",
    difficulty: "A1",
  },
  {
    id: "l20-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "nurse", hebrew: "אחות" },
      { id: "m2", english: "pilot", hebrew: "טייס" },
      { id: "m3", english: "chef", hebrew: "שף" },
      { id: "m4", english: "scientist", hebrew: "מדען" },
    ],
    difficulty: "A1",
  },
  {
    id: "l20-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "firefighter",
    questionType: "word",
    options: ["כבאי", "שוטר", "חייל", "רופא"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 21 – נסיעות וחופשה (Travel and Vacation)
  // ══════════════════════════════════════════════════
  {
    id: "l21-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "airplane",
    questionType: "word",
    options: ["מטוס", "רכבת", "אוטובוס", "ספינה"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l21-e2",
    type: "multiple-choice",
    instruction_he: "מה צריך לנסוע לחו\"ל?",
    question: "What do you need to travel abroad?",
    questionType: "sentence",
    options: ["דרכון", "ספר", "כדור", "מחשב"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l21-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "We are going on a {{blank}} to Paris.",
    answer: "trip",
    options: ["trip", "game", "test", "party"],
    hint_he: "מסע לחו\"ל",
    difficulty: "A1",
  },
  {
    id: "l21-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "hotel", hebrew: "מלון" },
      { id: "m2", english: "ticket", hebrew: "כרטיס" },
      { id: "m3", english: "luggage", hebrew: "מזוודה" },
      { id: "m4", english: "map", hebrew: "מפה" },
    ],
    difficulty: "A1",
  },
  {
    id: "l21-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "tourist",
    questionType: "word",
    options: ["תייר", "נהג", "מדריך", "שליח"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 22 – בריאות וגוף (Health and Body)
  // ══════════════════════════════════════════════════
  {
    id: "l22-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "hospital",
    questionType: "word",
    options: ["בית חולים", "בית ספר", "בנק", "מסעדה"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l22-e2",
    type: "multiple-choice",
    instruction_he: "במה רופא מודד חום?",
    question: "What does a doctor use to check temperature?",
    questionType: "sentence",
    options: ["מד חום", "מספריים", "מחשב", "עיפרון"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l22-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I have a {{blank}}. I need medicine.",
    answer: "headache",
    options: ["headache", "cold", "fever", "cough"],
    hint_he: "כאב בראש",
    difficulty: "A1",
  },
  {
    id: "l22-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "medicine", hebrew: "תרופה" },
      { id: "m2", english: "doctor", hebrew: "רופא" },
      { id: "m3", english: "fever", hebrew: "חום" },
      { id: "m4", english: "healthy", hebrew: "בריא" },
    ],
    difficulty: "A1",
  },
  {
    id: "l22-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "exercise",
    questionType: "word",
    options: ["פעילות גופנית", "אוכל", "שינה", "תרופה"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 23 – קניות ומסחר (Shopping and Commerce)
  // ══════════════════════════════════════════════════
  {
    id: "l23-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "supermarket",
    questionType: "word",
    options: ["סופרמרקט", "בית חולים", "בית ספר", "גן"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l23-e2",
    type: "multiple-choice",
    instruction_he: "מה מקבלים כשקונים משהו?",
    question: "What do you get when you buy something?",
    questionType: "sentence",
    options: ["קבלה", "מפה", "כרטיס", "מחברת"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l23-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "How much does it {{blank}}?",
    answer: "cost",
    options: ["cost", "have", "make", "say"],
    hint_he: "לשאול על מחיר",
    difficulty: "A1",
  },
  {
    id: "l23-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "price", hebrew: "מחיר" },
      { id: "m2", english: "discount", hebrew: "הנחה" },
      { id: "m3", english: "sale", hebrew: "מבצע" },
      { id: "m4", english: "receipt", hebrew: "קבלה" },
    ],
    difficulty: "A1",
  },
  {
    id: "l23-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "expensive",
    questionType: "word",
    options: ["יקר", "זול", "גדול", "קטן"],
    correctIndex: 0,
    difficulty: "A1",
  },

  // ══════════════════════════════════════════════════
  // LESSON 24 – הטבע סביבנו (Nature Around Us)
  // ══════════════════════════════════════════════════
  {
    id: "l24-e1",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "mountain",
    questionType: "word",
    options: ["הר", "ים", "נהר", "יער"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l24-e2",
    type: "multiple-choice",
    instruction_he: "לאן זורם נהר?",
    question: "Where does a river flow?",
    questionType: "sentence",
    options: ["לים", "להר", "לעיר", "לשמיים"],
    correctIndex: 0,
    difficulty: "A1",
  },
  {
    id: "l24-e3",
    type: "fill-in-blank",
    instruction_he: "בחרו את המילה החסרה",
    sentence: "I love to walk in the {{blank}}.",
    answer: "forest",
    options: ["forest", "desert", "ocean", "mountain"],
    hint_he: "מקום עם הרבה עצים",
    difficulty: "A1",
  },
  {
    id: "l24-e4",
    type: "matching",
    instruction_he: "חברו כל מילה לתרגום שלה",
    pairs: [
      { id: "m1", english: "ocean", hebrew: "אוקיינוס" },
      { id: "m2", english: "desert", hebrew: "מדבר" },
      { id: "m3", english: "lake", hebrew: "אגם" },
      { id: "m4", english: "island", hebrew: "אי" },
    ],
    difficulty: "A1",
  },
  {
    id: "l24-e5",
    type: "multiple-choice",
    instruction_he: "מה פירוש המילה?",
    question: "waterfall",
    questionType: "word",
    options: ["מפל", "אגם", "נהר", "ים"],
    correctIndex: 0,
    difficulty: "A1",
  },
];

/** Get an exercise by ID */
export function getExerciseById(id: string): Exercise | undefined {
  return ALL_EXERCISES.find((e) => e.id === id);
}

/** Get multiple exercises by IDs, in order */
export function getExercisesByIds(ids: string[]): Exercise[] {
  return ids
    .map((id) => getExerciseById(id))
    .filter((e): e is Exercise => e !== undefined);
}
