/** Grammar module content — 10 topics with expanded exercises */

export interface GrammarExercise {
  id: string;
  type: "choice" | "fillblank";
  instruction_he: string;
  /** For "choice": a full English sentence / question to display */
  question?: string;
  /** For "fillblank": sentence with ___ placeholder */
  sentence?: string;
  options: string[];
  correctIndex: number;
  explanation_he: string;
}

export interface GrammarTopic {
  id: string;
  title_he: string;
  title_en: string;
  icon: string;
  description_he: string;
  color: string; // Tailwind gradient classes
  exercises: GrammarExercise[];
}

export const GRAMMAR_TOPICS: GrammarTopic[] = [
  // ─── 1. Verb "to be" ───────────────────────────────────────────────────────
  {
    id: "g-be",
    title_he: "פועל To Be",
    title_en: "am / is / are",
    icon: "🟰",
    description_he: "לומדים: am, is, are — הווה",
    color: "from-blue-400 to-blue-600",
    exercises: [
      {
        id: "g-be-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ a student.",
        options: ["am", "is", "are", "be"],
        correctIndex: 0,
        explanation_he: "עם I משתמשים ב-am",
      },
      {
        id: "g-be-2",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ very tall.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "עם She / He / It משתמשים ב-is",
      },
      {
        id: "g-be-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ from Tel Aviv.",
        options: ["am", "is", "are", "be"],
        correctIndex: 2,
        explanation_he: "עם They / We / You משתמשים ב-are",
      },
      {
        id: "g-be-4",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "___ you ready?",
        options: ["Am", "Is", "Are", "Be"],
        correctIndex: 2,
        explanation_he: "בשאלה עם You משתמשים ב-Are",
      },
      {
        id: "g-be-5",
        type: "choice",
        instruction_he: "איזה משפט נכון?",
        question: "He ___ not here.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "עם He משתמשים ב-is (He is not = He isn't)",
      },
      {
        id: "g-be-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "We ___ happy today.",
        options: ["am", "is", "are", "be"],
        correctIndex: 2,
        explanation_he: "עם We משתמשים ב-are",
      },
      {
        id: "g-be-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "The dog ___ big.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "עם It/זה משתמשים ב-is",
      },
      {
        id: "g-be-8",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ I late?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 0,
        explanation_he: "שאלה עם I: Am I...?",
      },
      {
        id: "g-be-9",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "You and I ___ friends.",
        options: ["am", "is", "are", "be"],
        correctIndex: 2,
        explanation_he: "שני אנשים ← are",
      },
      {
        id: "g-be-10",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "The book ___ on the table.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "חפץ אחד ← is",
      },
      {
        id: "g-be-11",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "My parents ___ at home.",
        options: ["am", "is", "are", "be"],
        correctIndex: 2,
        explanation_he: "הורים = רבים ← are",
      },
      {
        id: "g-be-12",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ not tired.",
        options: ["am", "is", "are", "be"],
        correctIndex: 0,
        explanation_he: "שלילה: I am not...",
      },
      {
        id: "g-be-13",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ my sister.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "She ← is",
      },
      {
        id: "g-be-14",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ they students?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 2,
        explanation_he: "שאלה עם They: Are they?",
      },
      {
        id: "g-be-15",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "It ___ very hot outside.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "It ← is",
      },
    ],
  },
  // ─── 2. Present Simple ────────────────────────────────────────────────────
  {
    id: "g-present-simple",
    title_he: "הווה פשוט",
    title_en: "Present Simple",
    icon: "🔄",
    description_he: "שגרה ועובדות — I go, She goes",
    color: "from-green-400 to-green-600",
    exercises: [
      {
        id: "g-ps-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ to school every day.",
        options: ["go", "goes", "going", "went"],
        correctIndex: 1,
        explanation_he: "עם She/He/It מוסיפים -s לפועל: goes",
      },
      {
        id: "g-ps-2",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ like spinach.",
        options: ["don't", "doesn't", "not", "isn't"],
        correctIndex: 0,
        explanation_he: "עם I לשלילה משתמשים ב-don't",
      },
      {
        id: "g-ps-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ play football.",
        options: ["don't", "doesn't", "not", "isn't"],
        correctIndex: 1,
        explanation_he: "עם He/She לשלילה משתמשים ב-doesn't",
      },
      {
        id: "g-ps-4",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ you speak English?",
        options: ["Do", "Does", "Is", "Are"],
        correctIndex: 0,
        explanation_he: "עם You/I/They משתמשים ב-Do בשאלה",
      },
      {
        id: "g-ps-5",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "___ she live here?",
        options: ["Do", "Does", "Is", "Are"],
        correctIndex: 1,
        explanation_he: "עם She בשאלה משתמשים ב-Does",
      },
      {
        id: "g-ps-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ to bed early.",
        options: ["go", "goes", "going", "went"],
        correctIndex: 1,
        explanation_he: "He/She + s",
      },
      {
        id: "g-ps-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ soccer every weekend.",
        options: ["play", "plays", "playing", "played"],
        correctIndex: 0,
        explanation_he: "They - ללא s",
      },
      {
        id: "g-ps-8",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "My mother ___ breakfast every morning.",
        options: ["make", "makes", "making", "made"],
        correctIndex: 1,
        explanation_he: "She + makes",
      },
      {
        id: "g-ps-9",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ they live near school?",
        options: ["Do", "Does", "Is", "Are"],
        correctIndex: 0,
        explanation_he: "They בשאלה: Do",
      },
      {
        id: "g-ps-10",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ like pizza.",
        options: ["don't", "doesn't", "not", "no"],
        correctIndex: 1,
        explanation_he: "He שלילה: doesn't",
      },
      {
        id: "g-ps-11",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ to school by bus.",
        options: ["go", "goes", "went", "going"],
        correctIndex: 0,
        explanation_he: "I - ללא s",
      },
      {
        id: "g-ps-12",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ English very well.",
        options: ["speak", "speaks", "speaking", "spoke"],
        correctIndex: 1,
        explanation_he: "She + speaks",
      },
      {
        id: "g-ps-13",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "We ___ to the park on Fridays.",
        options: ["go", "goes", "went", "going"],
        correctIndex: 0,
        explanation_he: "We - ללא s",
      },
      {
        id: "g-ps-14",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ he have a dog?",
        options: ["Do", "Does", "Is", "Has"],
        correctIndex: 1,
        explanation_he: "He בשאלה: Does",
      },
      {
        id: "g-ps-15",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "Dogs ___ bones.",
        options: ["like", "likes", "liked", "liking"],
        correctIndex: 0,
        explanation_he: "רבים - ללא s",
      },
    ],
  },
  // ─── 3. Present Continuous ────────────────────────────────────────────────
  {
    id: "g-present-cont",
    title_he: "הווה מתמשך",
    title_en: "Present Continuous",
    icon: "▶️",
    description_he: "מה קורה עכשיו — I am reading",
    color: "from-teal-400 to-teal-600",
    exercises: [
      {
        id: "g-pc-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ a book right now.",
        options: ["read", "reads", "am reading", "is reading"],
        correctIndex: 2,
        explanation_he: "עם I משתמשים ב-am + פועל+ing",
      },
      {
        id: "g-pc-2",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ TV now.",
        options: ["watch", "watches", "am watching", "is watching"],
        correctIndex: 3,
        explanation_he: "עם She משתמשים ב-is + פועל+ing",
      },
      {
        id: "g-pc-3",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "They ___ outside. (play)",
        options: ["play", "plays", "are playing", "is playing"],
        correctIndex: 2,
        explanation_he: "עם They משתמשים ב-are + פועל+ing",
      },
      {
        id: "g-pc-4",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "___ you listening?",
        options: ["Do", "Does", "Am", "Are"],
        correctIndex: 3,
        explanation_he: "בשאלה הווה מתמשך עם You: Are you...?",
      },
      {
        id: "g-pc-5",
        type: "choice",
        instruction_he: "בחר את המשפט הנכון:",
        question: "I ___ sleeping.",
        options: ["am not", "is not", "are not", "not"],
        correctIndex: 0,
        explanation_he: "עם I לשלילה: I am not...",
      },
      {
        id: "g-pc-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ to music right now.",
        options: ["listen", "listens", "are listening", "is listening"],
        correctIndex: 3,
        explanation_he: "She + is + ing",
      },
      {
        id: "g-pc-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "We ___ lunch now.",
        options: ["eat", "eats", "is eating", "are eating"],
        correctIndex: 3,
        explanation_he: "We + are + ing",
      },
      {
        id: "g-pc-8",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ not working today.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "He is not working",
      },
      {
        id: "g-pc-9",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "What ___ you doing?",
        options: ["am", "is", "are", "do"],
        correctIndex: 2,
        explanation_he: "You: What are you doing?",
      },
      {
        id: "g-pc-10",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "The children ___ in the garden.",
        options: ["play", "plays", "is playing", "are playing"],
        correctIndex: 3,
        explanation_he: "רבים: are + ing",
      },
      {
        id: "g-pc-11",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ a book at the moment.",
        options: ["read", "reads", "am reading", "is reading"],
        correctIndex: 2,
        explanation_he: "I + am + ing",
      },
      {
        id: "g-pc-12",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "Look! It ___ outside!",
        options: ["rain", "rains", "am raining", "is raining"],
        correctIndex: 3,
        explanation_he: "It + is + ing",
      },
      {
        id: "g-pc-13",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ she sleeping now?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 1,
        explanation_he: "She: Is she...?",
      },
      {
        id: "g-pc-14",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ not eating.",
        options: ["am", "is", "are", "be"],
        correctIndex: 2,
        explanation_he: "They are not eating",
      },
      {
        id: "g-pc-15",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "My dad ___ a letter.",
        options: ["write", "writes", "am writing", "is writing"],
        correctIndex: 3,
        explanation_he: "He + is + ing",
      },
    ],
  },
  // ─── 4. Past Simple ───────────────────────────────────────────────────────
  {
    id: "g-past-simple",
    title_he: "עבר פשוט",
    title_en: "Past Simple",
    icon: "⏪",
    description_he: "מה קרה אתמול — I went, She walked",
    color: "from-purple-400 to-purple-600",
    exercises: [
      {
        id: "g-past-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "Yesterday I ___ to the park.",
        options: ["go", "goes", "went", "going"],
        correctIndex: 2,
        explanation_he: "go → went (פועל לא רגולרי)",
      },
      {
        id: "g-past-2",
        type: "fillblank",
        instruction_he: "כתוב את העבר של הפועל:",
        sentence: "I ___ to school yesterday. (walk)",
        options: ["walk", "walks", "walked", "walking"],
        correctIndex: 2,
        explanation_he: "walk → walked (פועל רגולרי — מוסיפים -ed)",
      },
      {
        id: "g-past-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ watch TV last night.",
        options: ["didn't", "doesn't", "wasn't", "weren't"],
        correctIndex: 0,
        explanation_he: "לשלילה בעבר: didn't + פועל בסיסי",
      },
      {
        id: "g-past-4",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ you see the movie?",
        options: ["Do", "Did", "Does", "Was"],
        correctIndex: 1,
        explanation_he: "שאלה בעבר: Did + גוף + פועל בסיסי",
      },
      {
        id: "g-past-5",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ a letter. (write)",
        options: ["write", "writes", "written", "wrote"],
        correctIndex: 3,
        explanation_he: "write → wrote (פועל לא רגולרי)",
      },
      {
        id: "g-past-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ happy yesterday.",
        options: ["is", "was", "were", "be"],
        correctIndex: 1,
        explanation_he: "She was (עבר של is)",
      },
      {
        id: "g-past-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ at the beach last summer.",
        options: ["is", "was", "were", "are"],
        correctIndex: 2,
        explanation_he: "They were (עבר של are)",
      },
      {
        id: "g-past-8",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ my homework last night.",
        options: ["do", "does", "did", "done"],
        correctIndex: 2,
        explanation_he: "I did (עבר של do)",
      },
      {
        id: "g-past-9",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ a letter to his friend.",
        options: ["write", "writes", "written", "wrote"],
        correctIndex: 3,
        explanation_he: "write → wrote",
      },
      {
        id: "g-past-10",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "We ___ the game yesterday.",
        options: ["lose", "looses", "lost", "losing"],
        correctIndex: 2,
        explanation_he: "lose → lost",
      },
      {
        id: "g-past-11",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ she at home last night?",
        options: ["Is", "Was", "Were", "Did"],
        correctIndex: 1,
        explanation_he: "שאלה: Was she...?",
      },
      {
        id: "g-past-12",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ see the movie.",
        options: ["didn't", "doesn't", "wasn't", "not"],
        correctIndex: 0,
        explanation_he: "לשלילה: didn't + פועל",
      },
      {
        id: "g-past-13",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "The teacher ___ us a story.",
        options: ["tell", "tells", "told", "telling"],
        correctIndex: 2,
        explanation_he: "tell → told",
      },
      {
        id: "g-past-14",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ to Paris last year.",
        options: ["go", "goes", "went", "gone"],
        correctIndex: 2,
        explanation_he: "go → went",
      },
      {
        id: "g-past-15",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ my keys.",
        options: ["lose", "lost", "loosing", "loosen"],
        correctIndex: 1,
        explanation_he: "lose → lost",
      },
    ],
  },
  // ─── 5. Can / Can't ───────────────────────────────────────────────────────
  {
    id: "g-can",
    title_he: "יכולת: Can",
    title_en: "Can / Can't",
    icon: "💪",
    description_he: "מה אני יכול לעשות — I can swim",
    color: "from-orange-400 to-orange-600",
    exercises: [
      {
        id: "g-can-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ swim very well.",
        options: ["can", "cans", "am can", "do can"],
        correctIndex: 0,
        explanation_he: "can לא משתנה לפי גוף — I can, She can",
      },
      {
        id: "g-can-2",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "She ___ ride a bike.",
        options: ["can't", "don't", "isn't", "hasn't"],
        correctIndex: 0,
        explanation_he: "can't = cannot (לא יכול)",
      },
      {
        id: "g-can-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "___ you help me?",
        options: ["Can", "Cans", "Do", "Are"],
        correctIndex: 0,
        explanation_he: "שאלה: Can + גוף + פועל?",
      },
      {
        id: "g-can-4",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ fly. (impossible)",
        options: ["can't", "don't", "isn't", "hasn't"],
        correctIndex: 0,
        explanation_he: "can't = cannot לשלילת יכולת",
      },
      {
        id: "g-can-5",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "What ___ you do?",
        options: ["can", "cans", "are", "do"],
        correctIndex: 0,
        explanation_he: "What can you do? — What + can + גוף + פועל?",
      },
      {
        id: "g-can-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She ___ speak three languages.",
        options: ["can", "cans", "could", "is can"],
        correctIndex: 0,
        explanation_he: "can לא משתנה",
      },
      {
        id: "g-can-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ swim very fast.",
        options: ["can", "cans", "are can", "do can"],
        correctIndex: 0,
        explanation_he: "can + פועל בסיסי",
      },
      {
        id: "g-can-8",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ I use your pen?",
        options: ["Can", "Could", "Am", "Do"],
        correctIndex: 0,
        explanation_he: "Can I...? = בקשה מנומסת",
      },
      {
        id: "g-can-9",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ read yet - he is only 3.",
        options: ["can't", "doesn't", "isn't", "not"],
        correctIndex: 0,
        explanation_he: "can't = לא מסוגל",
      },
      {
        id: "g-can-10",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "My cat ___ climb trees.",
        options: ["can", "cans", "is", "does"],
        correctIndex: 0,
        explanation_he: "can + פועל בסיסי",
      },
      {
        id: "g-can-11",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ play the guitar very well.",
        options: ["can", "am", "do", "have"],
        correctIndex: 0,
        explanation_he: "can + פועל",
      },
      {
        id: "g-can-12",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "Birds ___ fly.",
        options: ["can", "cans", "are", "do"],
        correctIndex: 0,
        explanation_he: "can - עובדה",
      },
      {
        id: "g-can-13",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ they come to the party?",
        options: ["Can", "Are", "Do", "Have"],
        correctIndex: 0,
        explanation_he: "Can they...?",
      },
      {
        id: "g-can-14",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "Fish ___ breathe underwater.",
        options: ["can", "cans", "are", "do"],
        correctIndex: 0,
        explanation_he: "עובדה: fish can",
      },
      {
        id: "g-can-15",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ run fast today - my leg hurts.",
        options: ["can't", "don't", "aren't", "haven't"],
        correctIndex: 0,
        explanation_he: "can't = אי יכולת",
      },
    ],
  },
  // ─── 6. Going to ──────────────────────────────────────────────────────────
  {
    id: "g-going-to",
    title_he: "עתיד: Going To",
    title_en: "Going to",
    icon: "🚀",
    description_he: "תוכניות לעתיד — I am going to...",
    color: "from-cyan-400 to-cyan-600",
    exercises: [
      {
        id: "g-gt-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ visit my grandmother tomorrow.",
        options: ["going to", "go to", "am going to", "am go to"],
        correctIndex: 2,
        explanation_he: "עם I: I am going to + פועל",
      },
      {
        id: "g-gt-2",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "She is going to ___ English.",
        options: ["study", "studies", "studied", "studying"],
        correctIndex: 0,
        explanation_he: "אחרי going to בא פועל בסיסי",
      },
      {
        id: "g-gt-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "___ you going to come to the party?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 2,
        explanation_he: "שאלה עם You: Are you going to...?",
      },
      {
        id: "g-gt-4",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He is going to ___ home.",
        options: ["goes", "go", "going", "went"],
        correctIndex: 1,
        explanation_he: "אחרי going to: פועל בסיסי (go, not goes)",
      },
      {
        id: "g-gt-5",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "What ___ they going to do?",
        options: ["am", "is", "are", "do"],
        correctIndex: 2,
        explanation_he: "עם They: What are they going to...?",
      },
      {
        id: "g-gt-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "They ___ go to the movies tonight.",
        options: ["go to", "going to", "are going to", "is going to"],
        correctIndex: 2,
        explanation_he: "They + are going to",
      },
      {
        id: "g-gt-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He ___ buy a new bike.",
        options: ["go to", "going to", "are going to", "is going to"],
        correctIndex: 3,
        explanation_he: "He + is going to",
      },
      {
        id: "g-gt-8",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "I ___ not eat meat anymore.",
        options: ["go to", "going to", "am going to", "is going to"],
        correctIndex: 2,
        explanation_he: "I + am going to",
      },
      {
        id: "g-gt-9",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "We ___ visit our grandparents.",
        options: ["go to", "going to", "are going to", "is going to"],
        correctIndex: 2,
        explanation_he: "We + are going to",
      },
      {
        id: "g-gt-10",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "She is going to ___ a doctor.",
        options: ["be", "is", "am", "being"],
        correctIndex: 0,
        explanation_he: "going to + פועל בסיסי = be",
      },
      {
        id: "g-gt-11",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "It ___ rain today.",
        options: ["go to rain", "going to rain", "is going to rain", "are going to rain"],
        correctIndex: 2,
        explanation_he: "It is going to rain",
      },
      {
        id: "g-gt-12",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ you going to study?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 2,
        explanation_he: "You: Are you going to...?",
      },
      {
        id: "g-gt-13",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "I am not going to ___ TV tonight.",
        options: ["watch", "watching", "watched", "watches"],
        correctIndex: 0,
        explanation_he: "going to + פועל בסיסי",
      },
      {
        id: "g-gt-14",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "He is going to ___ his homework.",
        options: ["do", "does", "did", "doing"],
        correctIndex: 0,
        explanation_he: "going to + do",
      },
      {
        id: "g-gt-15",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "She is going to ___ happy about this.",
        options: ["be", "is", "am", "will"],
        correctIndex: 0,
        explanation_he: "going to + be",
      },
    ],
  },
  // ─── 7. Imperatives ───────────────────────────────────────────────────────
  {
    id: "g-imperatives",
    title_he: "פקודות",
    title_en: "Imperatives",
    icon: "📢",
    description_he: "הוראות ופקודות — Open, Don't run",
    color: "from-red-400 to-red-600",
    exercises: [
      {
        id: "g-imp-1",
        type: "choice",
        instruction_he: "בחר את הפקודה הנכונה:",
        question: "___ the door, please.",
        options: ["Open", "Opens", "Opening", "Opened"],
        correctIndex: 0,
        explanation_he: "פקודה = פועל בסיסי: Open (לא Opens!)",
      },
      {
        id: "g-imp-2",
        type: "fillblank",
        instruction_he: "השלם את הפקודה השלילית:",
        sentence: "___ run in the hallway!",
        options: ["Don't", "Doesn't", "Not", "No"],
        correctIndex: 0,
        explanation_he: "פקודה שלילית: Don't + פועל",
      },
      {
        id: "g-imp-3",
        type: "choice",
        instruction_he: "בחר את הפקודה הנכונה:",
        question: "Please ___ down.",
        options: ["sit", "sits", "sitting", "sat"],
        correctIndex: 0,
        explanation_he: "Please + פועל בסיסי = פקודה מנומסת",
      },
      {
        id: "g-imp-4",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "___ play together!",
        options: ["Let's", "Lets", "Let", "We"],
        correctIndex: 0,
        explanation_he: "Let's = Let us — הצעה לפעולה משותפת",
      },
      {
        id: "g-imp-5",
        type: "fillblank",
        instruction_he: "השלם את הפקודה:",
        sentence: "___ the window, please. (close)",
        options: ["Close", "Closes", "Closed", "Closing"],
        correctIndex: 0,
        explanation_he: "פקודה = פועל בסיסי: Close",
      },
      {
        id: "g-imp-6",
        type: "choice",
        instruction_he: "בחר את הפקודה הנכונה:",
        question: "Please ___ quiet!",
        options: ["be", "are", "is", "am"],
        correctIndex: 0,
        explanation_he: "פקודה: be (פועל to be בסיסי)",
      },
      {
        id: "g-imp-7",
        type: "fillblank",
        instruction_he: "השלם את הפקודה:",
        sentence: "___ your hands before eating.",
        options: ["Wash", "Washes", "Washing", "Washed"],
        correctIndex: 0,
        explanation_he: "פקודה: פועל בסיסי",
      },
      {
        id: "g-imp-8",
        type: "fillblank",
        instruction_he: "השלם את הפקודה השלילית:",
        sentence: "___ talk in class!",
        options: ["Don't", "Doesn't", "Not", "No"],
        correctIndex: 0,
        explanation_he: "פקודה שלילית: Don't",
      },
      {
        id: "g-imp-9",
        type: "fillblank",
        instruction_he: "השלם את הפקודה:",
        sentence: "Always ___ your homework.",
        options: ["do", "does", "doing", "did"],
        correctIndex: 0,
        explanation_he: "פקודה: do",
      },
      {
        id: "g-imp-10",
        type: "fillblank",
        instruction_he: "השלם את הפקודה השלילית:",
        sentence: "___ forget your bag!",
        options: ["Don't", "Doesn't", "Not", "Never"],
        correctIndex: 0,
        explanation_he: "Don't forget",
      },
    ],
  },
  // ─── 8. Comparatives & Superlatives ──────────────────────────────────────
  {
    id: "g-comparatives",
    title_he: "השוואה",
    title_en: "Comparatives & Superlatives",
    icon: "📊",
    description_he: "taller, tallest, more beautiful",
    color: "from-yellow-400 to-yellow-600",
    exercises: [
      {
        id: "g-comp-1",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She is ___ than me.",
        options: ["tall", "taller", "tallest", "more tall"],
        correctIndex: 1,
        explanation_he: "השוואה: tall → taller (מוסיפים -er)",
      },
      {
        id: "g-comp-2",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "He is the ___ in the class. (tall)",
        options: ["tall", "taller", "tallest", "most tall"],
        correctIndex: 2,
        explanation_he: "עליון: the tallest (מוסיפים -est)",
      },
      {
        id: "g-comp-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "This book is ___ interesting.",
        options: ["more", "most", "many", "much"],
        correctIndex: 0,
        explanation_he: "מילים ארוכות: more + תואר השם",
      },
      {
        id: "g-comp-4",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "This is the ___ beautiful flower.",
        options: ["more", "most", "better", "best"],
        correctIndex: 1,
        explanation_he: "עליון של מילה ארוכה: the most + תואר השם",
      },
      {
        id: "g-comp-5",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "This box is ___ than that one. (big)",
        options: ["big", "bigger", "biggest", "more big"],
        correctIndex: 1,
        explanation_he: "big → bigger (מכפילים עיצור + -er)",
      },
      {
        id: "g-comp-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "A lion is ___ than a cat.",
        options: ["big", "bigger", "biggest", "most big"],
        correctIndex: 1,
        explanation_he: "big → bigger",
      },
      {
        id: "g-comp-7",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "English is ___ than math (for me).",
        options: ["easy", "more easy", "easier", "easiest"],
        correctIndex: 2,
        explanation_he: "easy → easier",
      },
      {
        id: "g-comp-8",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "This is the ___ movie I have seen.",
        options: ["good", "better", "best", "most good"],
        correctIndex: 2,
        explanation_he: "good → best (שלא רגולרי)",
      },
      {
        id: "g-comp-9",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "She is ___ than her brother.",
        options: ["young", "younger", "youngest", "more young"],
        correctIndex: 1,
        explanation_he: "young → younger",
      },
      {
        id: "g-comp-10",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "Today is ___ than yesterday.",
        options: ["hot", "hotter", "hottest", "more hot"],
        correctIndex: 1,
        explanation_he: "hot → hotter (כפל עיצור)",
      },
      {
        id: "g-comp-11",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "He is the ___ student in the class.",
        options: ["good", "better", "best", "most good"],
        correctIndex: 2,
        explanation_he: "the best",
      },
      {
        id: "g-comp-12",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "My bag is ___ than yours.",
        options: ["heavy", "more heavy", "heavier", "heaviest"],
        correctIndex: 2,
        explanation_he: "heavy → heavier",
      },
      {
        id: "g-comp-13",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "This is the ___ day of the year.",
        options: ["cold", "colder", "coldest", "most cold"],
        correctIndex: 2,
        explanation_he: "the coldest",
      },
    ],
  },
  // ─── 9. There is / There are ──────────────────────────────────────────────
  {
    id: "g-there-is",
    title_he: "There is / There are",
    title_en: "There is / There are",
    icon: "📍",
    description_he: "יש — There is a cat, There are dogs",
    color: "from-pink-400 to-pink-600",
    exercises: [
      {
        id: "g-ti-1",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "There ___ a book on the table.",
        options: ["am", "is", "are", "have"],
        correctIndex: 1,
        explanation_he: "יחיד: There is a...",
      },
      {
        id: "g-ti-2",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "There ___ three cats in the garden.",
        options: ["is", "are", "be", "have"],
        correctIndex: 1,
        explanation_he: "רבים: There are...",
      },
      {
        id: "g-ti-3",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "___ there a park near your house?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 1,
        explanation_he: "שאלה ביחיד: Is there a...?",
      },
      {
        id: "g-ti-4",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "Are there ___ apples?",
        options: ["a", "an", "any", "some"],
        correctIndex: 2,
        explanation_he: "בשאלה ובשלילה משתמשים ב-any",
      },
      {
        id: "g-ti-5",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "There ___ not a dog here.",
        options: ["am", "is", "are", "be"],
        correctIndex: 1,
        explanation_he: "שלילה ביחיד: There is not / There isn't",
      },
      {
        id: "g-ti-6",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "There ___ some water in the bottle.",
        options: ["am", "is", "are", "have"],
        correctIndex: 1,
        explanation_he: "מים (uncountable) ← is",
      },
      {
        id: "g-ti-7",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "Are there ___ children in the park?",
        options: ["a", "an", "any", "some"],
        correctIndex: 2,
        explanation_he: "שאלה ← any",
      },
      {
        id: "g-ti-8",
        type: "choice",
        instruction_he: "בחר את הצורה הנכונה:",
        question: "There ___ a lot of trees in the forest.",
        options: ["is", "are", "be", "have"],
        correctIndex: 1,
        explanation_he: "רבים ← are",
      },
      {
        id: "g-ti-9",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "There isn't ___ milk in the fridge.",
        options: ["a", "an", "any", "some"],
        correctIndex: 2,
        explanation_he: "שלילה ← any",
      },
      {
        id: "g-ti-10",
        type: "fillblank",
        instruction_he: "השלם את השאלה:",
        sentence: "___ there a bathroom near here?",
        options: ["Am", "Is", "Are", "Do"],
        correctIndex: 1,
        explanation_he: "Is there a...? יחיד",
      },
    ],
  },
  // ─── 10. Pronouns ─────────────────────────────────────────────────────────
  {
    id: "g-pronouns",
    title_he: "כינויי גוף",
    title_en: "Pronouns",
    icon: "👤",
    description_he: "I, me, my, mine — he, him, his",
    color: "from-indigo-400 to-indigo-600",
    exercises: [
      {
        id: "g-pro-1",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "___ am a student.",
        options: ["I", "Me", "My", "Mine"],
        correctIndex: 0,
        explanation_he: "כינוי נושא: I, You, He, She, It, We, They",
      },
      {
        id: "g-pro-2",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "This is ___ book. (שלי)",
        options: ["I", "me", "my", "mine"],
        correctIndex: 2,
        explanation_he: "כינוי שייכות לפני שם עצם: my, your, his, her",
      },
      {
        id: "g-pro-3",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "She gave ___ the book. (לי)",
        options: ["I", "me", "my", "mine"],
        correctIndex: 1,
        explanation_he: "כינוי מושא: me, you, him, her, us, them",
      },
      {
        id: "g-pro-4",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "The dog is ___. (שלה — כינוי עצמאי)",
        options: ["her", "hers", "she", "his"],
        correctIndex: 1,
        explanation_he: "כינוי שייכות עצמאי: mine, yours, his, hers",
      },
      {
        id: "g-pro-5",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "___ is the tallest in the class.",
        options: ["He", "Him", "His", "Her"],
        correctIndex: 0,
        explanation_he: "כינוי נושא: He (לא Him שהוא מושא)",
      },
      {
        id: "g-pro-6",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "Give ___ the book, please. (לו)",
        options: ["he", "him", "his", "her"],
        correctIndex: 1,
        explanation_he: "him = כינוי מושא זכר",
      },
      {
        id: "g-pro-7",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "This bag is ___. (שלנו)",
        options: ["our", "we", "ours", "us"],
        correctIndex: 2,
        explanation_he: "ours = כינוי שייכות עצמאי",
      },
      {
        id: "g-pro-8",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "Tell ___ the answer. (להם)",
        options: ["they", "their", "theirs", "them"],
        correctIndex: 3,
        explanation_he: "them = כינוי מושא",
      },
      {
        id: "g-pro-9",
        type: "choice",
        instruction_he: "בחר את הכינוי הנכון:",
        question: "Is this pen ___? (שלך)",
        options: ["your", "you", "yours", "yourself"],
        correctIndex: 2,
        explanation_he: "yours = כינוי שייכות עצמאי",
      },
      {
        id: "g-pro-10",
        type: "fillblank",
        instruction_he: "השלם את המשפט:",
        sentence: "___ is my best friend. (הוא)",
        options: ["He", "Him", "His", "Her"],
        correctIndex: 0,
        explanation_he: "נושא: He",
      },
    ],
  },

  // ─── Present Continuous ───────────────────────────────────────────────────
  {
    id: "g-cont",
    title_he: "הווה ממשיך",
    title_en: "Present Continuous",
    icon: "▶️",
    description_he: "פעולות שקורות עכשיו ותוכניות לעתיד קרוב",
    color: "from-orange-400 to-amber-500",
    exercises: [
      { id: "g-cont-1", type: "choice", instruction_he: "בחר את הצורה הנכונה:", question: "She ___ listening to music right now.", options: ["is", "are", "am", "be"], correctIndex: 0, explanation_he: "she + is + V-ing" },
      { id: "g-cont-2", type: "fillblank", instruction_he: "השלם:", sentence: "They ___ playing football in the yard.", options: ["is", "are", "am", "be"], correctIndex: 1, explanation_he: "they + are + V-ing" },
      { id: "g-cont-3", type: "choice", instruction_he: "בחר:", question: "I ___ doing my homework now.", options: ["are", "is", "am", "be"], correctIndex: 2, explanation_he: "I + am + V-ing" },
      { id: "g-cont-4", type: "fillblank", instruction_he: "השלם:", sentence: "The baby ___ sleeping.", options: ["are", "is", "am", "be"], correctIndex: 1, explanation_he: "the baby = גוף שלישי יחיד: is" },
      { id: "g-cont-5", type: "choice", instruction_he: "בחר:", question: "What are you ___?", options: ["do", "does", "doing", "done"], correctIndex: 2, explanation_he: "are you + V-ing" },
      { id: "g-cont-6", type: "fillblank", instruction_he: "השלם:", sentence: "We ___ having a great time!", options: ["is", "are", "am", "be"], correctIndex: 1, explanation_he: "we + are" },
      { id: "g-cont-7", type: "choice", instruction_he: "בחר:", question: "He is ___ a book right now.", options: ["read", "reads", "reading", "readed"], correctIndex: 2, explanation_he: "is + reading (V-ing)" },
      { id: "g-cont-8", type: "fillblank", instruction_he: "השלם:", sentence: "Look! It ___ raining.", options: ["are", "is", "am", "do"], correctIndex: 1, explanation_he: "it + is" },
      { id: "g-cont-9", type: "choice", instruction_he: "בחר:", question: "Are they ___?", options: ["come", "came", "coming", "comes"], correctIndex: 2, explanation_he: "Are they + coming?" },
      { id: "g-cont-10", type: "fillblank", instruction_he: "השלם:", sentence: "I am ___ to the market this afternoon.", options: ["go", "goes", "going", "gone"], correctIndex: 2, explanation_he: "am + going (תוכנית עתידית)" },
      { id: "g-cont-11", type: "choice", instruction_he: "בחר:", question: "She is not ___ the TV.", options: ["watch", "watches", "watching", "watched"], correctIndex: 2, explanation_he: "is not + watching" },
      { id: "g-cont-12", type: "fillblank", instruction_he: "השלם:", sentence: "The children ___ running in the park.", options: ["is", "are", "am", "be"], correctIndex: 1, explanation_he: "children = רבים: are" },
      { id: "g-cont-13", type: "choice", instruction_he: "בחר:", question: "Dad ___ cooking dinner right now.", options: ["are", "is", "am", "be"], correctIndex: 1, explanation_he: "dad = גוף שלישי יחיד: is" },
      { id: "g-cont-14", type: "fillblank", instruction_he: "השלם:", sentence: "Why ___ you laughing?", options: ["am", "is", "are", "be"], correctIndex: 2, explanation_he: "you + are" },
      { id: "g-cont-15", type: "choice", instruction_he: "בחר:", question: "My friends are ___ to a movie tonight.", options: ["go", "going", "goes", "went"], correctIndex: 1, explanation_he: "are + going (תוכנית לעתיד קרוב)" },
    ],
  },

  // ─── Present Simple Advanced ──────────────────────────────────────────────
  {
    id: "g-present-exp",
    title_he: "הווה פשוט — שלילות ושאלות",
    title_en: "Present Simple: negatives & questions",
    icon: "❓",
    description_he: "שלילות, שאלות ושגרה יומיומית",
    color: "from-teal-400 to-cyan-600",
    exercises: [
      { id: "g-ps-e1", type: "choice", instruction_he: "בחר את הצורה הנכונה:", question: "She ___ not like spicy food.", options: ["do", "does", "is", "has"], correctIndex: 1, explanation_he: "שלילה עם he/she/it: does not" },
      { id: "g-ps-e2", type: "fillblank", instruction_he: "השלם:", sentence: "___ your brother play football?", options: ["Do", "Does", "Is", "Has"], correctIndex: 1, explanation_he: "שאלה עם he/she/it: Does" },
      { id: "g-ps-e3", type: "choice", instruction_he: "בחר:", question: "We ___ not watch TV on weekdays.", options: ["does", "do", "are", "have"], correctIndex: 1, explanation_he: "שלילה עם we: do not" },
      { id: "g-ps-e4", type: "fillblank", instruction_he: "השלם:", sentence: "My dad ___ to work by car.", options: ["go", "goes", "going", "gone"], correctIndex: 1, explanation_he: "he/she/it: פועל + s" },
      { id: "g-ps-e5", type: "choice", instruction_he: "בחר שאלה נכונה:", question: "___ you like ice cream?", options: ["Does", "Do", "Is", "Are"], correctIndex: 1, explanation_he: "שאלה עם you: Do" },
      { id: "g-ps-e6", type: "fillblank", instruction_he: "השלם:", sentence: "The sun ___ in the east.", options: ["rise", "rises", "rising", "risen"], correctIndex: 1, explanation_he: "עובדת טבע: the sun rises" },
      { id: "g-ps-e7", type: "choice", instruction_he: "בחר:", question: "My sister ___ tennis every Sunday.", options: ["play", "plays", "is play", "playing"], correctIndex: 1, explanation_he: "she: plays" },
      { id: "g-ps-e8", type: "fillblank", instruction_he: "השלם:", sentence: "They ___ live in Jerusalem.", options: ["doesn't", "don't", "isn't", "aren't"], correctIndex: 1, explanation_he: "שלילה עם they: don't" },
      { id: "g-ps-e9", type: "choice", instruction_he: "בחר:", question: "What time ___ the school start?", options: ["do", "does", "is", "has"], correctIndex: 1, explanation_he: "the school = גוף שלישי יחיד: does" },
      { id: "g-ps-e10", type: "fillblank", instruction_he: "השלם:", sentence: "___ he speak Arabic?", options: ["Do", "Does", "Is", "Has"], correctIndex: 1, explanation_he: "שאלה: Does + he" },
      { id: "g-ps-e11", type: "choice", instruction_he: "בחר:", question: "Birds ___ fly south in winter.", options: ["does", "do", "are", "have"], correctIndex: 1, explanation_he: "birds = רבים: do" },
      { id: "g-ps-e12", type: "fillblank", instruction_he: "השלם:", sentence: "Water ___ at 100 degrees.", options: ["boil", "boils", "boiling", "boiled"], correctIndex: 1, explanation_he: "עובדת מדעית: boils" },
      { id: "g-ps-e13", type: "choice", instruction_he: "בחר:", question: "She ___ her teeth twice a day.", options: ["brush", "brushes", "is brush", "brushing"], correctIndex: 1, explanation_he: "she + brushes (es אחרי sh)" },
      { id: "g-ps-e14", type: "fillblank", instruction_he: "השלם:", sentence: "He ___ not eat vegetables.", options: ["don't", "doesn't", "isn't", "hasn't"], correctIndex: 1, explanation_he: "he + doesn't" },
      { id: "g-ps-e15", type: "choice", instruction_he: "בחר:", question: "I ___ get up at 7 every morning.", options: ["does", "do", "am", "have"], correctIndex: 1, explanation_he: "I + do (אינדיקטיב)" },
    ],
  },

  // ─── Past Simple Advanced ─────────────────────────────────────────────────
  {
    id: "g-past-exp",
    title_he: "עבר — פעלים לא-רגילים",
    title_en: "Past Simple: irregular verbs",
    icon: "⏮️",
    description_he: "פעלים לא-רגילים נפוצים בעבר",
    color: "from-purple-400 to-violet-600",
    exercises: [
      { id: "g-pa-e1", type: "choice", instruction_he: "עבר של: go", question: "Yesterday I ___ to the park.", options: ["goed", "went", "gone", "going"], correctIndex: 1, explanation_he: "go → went" },
      { id: "g-pa-e2", type: "fillblank", instruction_he: "השלם:", sentence: "She ___ a letter to her friend.", options: ["write", "wrote", "written", "writing"], correctIndex: 1, explanation_he: "write → wrote" },
      { id: "g-pa-e3", type: "choice", instruction_he: "עבר של: eat", question: "The dog ___ all the food.", options: ["eated", "ate", "eaten", "eating"], correctIndex: 1, explanation_he: "eat → ate" },
      { id: "g-pa-e4", type: "fillblank", instruction_he: "השלם:", sentence: "We ___ a great movie last night.", options: ["see", "saw", "seen", "seeing"], correctIndex: 1, explanation_he: "see → saw" },
      { id: "g-pa-e5", type: "choice", instruction_he: "בחר:", question: "He ___ his homework before dinner.", options: ["do", "does", "did", "done"], correctIndex: 2, explanation_he: "do → did" },
      { id: "g-pa-e6", type: "fillblank", instruction_he: "השלם:", sentence: "They ___ in the sea for two hours.", options: ["swim", "swam", "swum", "swimming"], correctIndex: 1, explanation_he: "swim → swam" },
      { id: "g-pa-e7", type: "choice", instruction_he: "שאלה בעבר:", question: "___ you sleep well last night?", options: ["Did", "Do", "Does", "Was"], correctIndex: 0, explanation_he: "שאלה בעבר: Did + subject + V" },
      { id: "g-pa-e8", type: "fillblank", instruction_he: "השלם שלילה:", sentence: "I ___ not understand the question.", options: ["did", "do", "does", "was"], correctIndex: 0, explanation_he: "שלילה בעבר: did not + V" },
      { id: "g-pa-e9", type: "choice", instruction_he: "עבר של: have", question: "She ___ a birthday party.", options: ["haved", "had", "have", "has"], correctIndex: 1, explanation_he: "have → had" },
      { id: "g-pa-e10", type: "fillblank", instruction_he: "השלם:", sentence: "My mom ___ a delicious cake.", options: ["make", "made", "makes", "making"], correctIndex: 1, explanation_he: "make → made" },
      { id: "g-pa-e11", type: "choice", instruction_he: "עבר של: run", question: "The cat ___ away quickly.", options: ["runned", "ran", "run", "running"], correctIndex: 1, explanation_he: "run → ran" },
      { id: "g-pa-e12", type: "fillblank", instruction_he: "השלם:", sentence: "I ___ my friend at the mall.", options: ["meet", "met", "meets", "meeting"], correctIndex: 1, explanation_he: "meet → met" },
      { id: "g-pa-e13", type: "choice", instruction_he: "עבר של: give", question: "She ___ me a book.", options: ["gived", "gave", "given", "gives"], correctIndex: 1, explanation_he: "give → gave" },
      { id: "g-pa-e14", type: "fillblank", instruction_he: "השלם:", sentence: "The boy ___ his bike to school.", options: ["ride", "rode", "ridden", "riding"], correctIndex: 1, explanation_he: "ride → rode" },
      { id: "g-pa-e15", type: "choice", instruction_he: "עבר של: take", question: "He ___ the bus to school.", options: ["taked", "took", "taken", "taking"], correctIndex: 1, explanation_he: "take → took" },
    ],
  },

  // ─── Future Tenses ────────────────────────────────────────────────────────
  {
    id: "g-future",
    title_he: "עתיד — Will ו-Going to",
    title_en: "Will / Going to",
    icon: "🔮",
    description_he: "תוכניות, תחזיות והחלטות עתידיות",
    color: "from-indigo-400 to-blue-600",
    exercises: [
      { id: "g-fut-1", type: "choice", instruction_he: "בחר:", question: "It is very cloudy. It ___ rain.", options: ["will", "is going to", "would", "shall"], correctIndex: 1, explanation_he: "going to = תחזית עם ראיות" },
      { id: "g-fut-2", type: "fillblank", instruction_he: "השלם:", sentence: "I ___ help you with your bags.", options: ["will", "am going to", "would", "shall"], correctIndex: 0, explanation_he: "will = החלטה ספונטנית" },
      { id: "g-fut-3", type: "choice", instruction_he: "בחר:", question: "We ___ visit grandma tomorrow. (תוכנית)", options: ["will", "are going to", "would", "shall"], correctIndex: 1, explanation_he: "going to = תוכנית קבועה מראש" },
      { id: "g-fut-4", type: "fillblank", instruction_he: "השלם:", sentence: "___ you be at school tomorrow?", options: ["Will", "Are", "Do", "Have"], correctIndex: 0, explanation_he: "Will you...? — שאלה בעתיד" },
      { id: "g-fut-5", type: "choice", instruction_he: "בחר:", question: "I promise I ___ be late.", options: ["will not", "am not going to", "would not", "don't"], correctIndex: 0, explanation_he: "will not = הבטחה" },
      { id: "g-fut-6", type: "fillblank", instruction_he: "השלם:", sentence: "She is going to ___ a doctor.", options: ["be", "is", "will be", "was"], correctIndex: 0, explanation_he: "going to + פועל בסיסי" },
      { id: "g-fut-7", type: "choice", instruction_he: "בחר:", question: "Look at those clouds! It ___ snow!", options: ["will", "is going to", "would", "shall"], correctIndex: 1, explanation_he: "ראיות ברורות → going to" },
      { id: "g-fut-8", type: "fillblank", instruction_he: "השלם:", sentence: "I think it ___ be a great day.", options: ["will", "is going to", "would", "shall"], correctIndex: 0, explanation_he: "דעה/תחזית: will" },
      { id: "g-fut-9", type: "choice", instruction_he: "בחר:", question: "Don't worry! Everything ___ be okay.", options: ["is going to", "will", "would", "shall"], correctIndex: 1, explanation_he: "הרגעה/הבטחה: will" },
      { id: "g-fut-10", type: "fillblank", instruction_he: "השלם:", sentence: "They ___ not come to the party.", options: ["will", "are going to", "would", "do"], correctIndex: 0, explanation_he: "will not" },
      { id: "g-fut-11", type: "choice", instruction_he: "בחר:", question: "She ___ study medicine. (תוכנית)", options: ["will", "is going to", "would", "shall"], correctIndex: 1, explanation_he: "going to = תוכנית" },
      { id: "g-fut-12", type: "fillblank", instruction_he: "השלם:", sentence: "What ___ you do this summer?", options: ["will", "are going to", "would", "shall"], correctIndex: 0, explanation_he: "What will you do? — שאלה כללית" },
      { id: "g-fut-13", type: "choice", instruction_he: "בחר:", question: "I ___ open the door for you. (ספונטני)", options: ["am going to", "will", "would", "shall"], correctIndex: 1, explanation_he: "will = החלטה עכשווית" },
      { id: "g-fut-14", type: "fillblank", instruction_he: "השלם:", sentence: "We ___ go to the park if the weather is nice.", options: ["will", "is going to", "would", "shall"], correctIndex: 0, explanation_he: "will" },
      { id: "g-fut-15", type: "choice", instruction_he: "בחר:", question: "___ I open the window?", options: ["Will", "Shall", "Am going to", "Do"], correctIndex: 1, explanation_he: "Shall I...? = הצעה מנומסת" },
    ],
  },

  // ─── Conditionals ─────────────────────────────────────────────────────────
  {
    id: "g-conditionals",
    title_he: "משפטי תנאי",
    title_en: "If / Conditionals",
    icon: "🔀",
    description_he: "If + present, will... — תנאים ותוצאות",
    color: "from-pink-400 to-rose-600",
    exercises: [
      { id: "g-cond-1", type: "choice", instruction_he: "בחר:", question: "If it rains, I ___ an umbrella.", options: ["take", "will take", "took", "taking"], correctIndex: 1, explanation_he: "First Conditional: If + present, will + V" },
      { id: "g-cond-2", type: "fillblank", instruction_he: "השלם:", sentence: "If you study hard, you ___ pass the test.", options: ["will", "would", "can", "might"], correctIndex: 0, explanation_he: "First Conditional: will" },
      { id: "g-cond-3", type: "choice", instruction_he: "בחר:", question: "If she is hungry, she ___ something to eat.", options: ["finds", "will find", "found", "finding"], correctIndex: 1, explanation_he: "If + present → will + V" },
      { id: "g-cond-4", type: "fillblank", instruction_he: "השלם:", sentence: "If it ___ sunny tomorrow, we will go to the beach.", options: ["is", "will be", "was", "were"], correctIndex: 0, explanation_he: "If-clause: present simple" },
      { id: "g-cond-5", type: "choice", instruction_he: "בחר:", question: "If you eat too much, you ___ sick.", options: ["feel", "will feel", "felt", "feeling"], correctIndex: 1, explanation_he: "will feel" },
      { id: "g-cond-6", type: "fillblank", instruction_he: "השלם:", sentence: "If I have money, I ___ a new phone.", options: ["buy", "will buy", "bought", "buying"], correctIndex: 1, explanation_he: "will buy" },
      { id: "g-cond-7", type: "choice", instruction_he: "בחר:", question: "If they don't hurry, they ___ late.", options: ["are", "will be", "were", "being"], correctIndex: 1, explanation_he: "will be" },
      { id: "g-cond-8", type: "fillblank", instruction_he: "השלם:", sentence: "What will you do if you ___ the exam?", options: ["fail", "will fail", "failed", "failing"], correctIndex: 0, explanation_he: "If-clause: present simple" },
      { id: "g-cond-9", type: "choice", instruction_he: "בחר:", question: "If water is heated to 100 degrees, it ___.", options: ["boil", "boils", "will boil", "boiled"], correctIndex: 1, explanation_he: "Zero Conditional: always true" },
      { id: "g-cond-10", type: "fillblank", instruction_he: "השלם:", sentence: "If you need help, just ___.", options: ["ask", "will ask", "asking", "asked"], correctIndex: 0, explanation_he: "If + present, imperative" },
      { id: "g-cond-11", type: "choice", instruction_he: "בחר:", question: "If she calls, I ___ her back.", options: ["call", "will call", "called", "calling"], correctIndex: 1, explanation_he: "will call" },
      { id: "g-cond-12", type: "fillblank", instruction_he: "השלם:", sentence: "If I ___ you, I will bring a jacket.", options: ["am", "were", "is", "be"], correctIndex: 0, explanation_he: "If I am (תנאי אמיתי)" },
      { id: "g-cond-13", type: "choice", instruction_he: "בחר:", question: "We ___ go to the park if the weather is nice.", options: ["can", "could", "will", "would"], correctIndex: 2, explanation_he: "will go" },
      { id: "g-cond-14", type: "fillblank", instruction_he: "השלם:", sentence: "If it ___ cold, we stay inside.", options: ["is", "will be", "was", "were"], correctIndex: 0, explanation_he: "Zero conditional: if + present" },
      { id: "g-cond-15", type: "choice", instruction_he: "בחר:", question: "If you press this button, the light ___.", options: ["turns on", "will turn on", "turned on", "turn on"], correctIndex: 0, explanation_he: "Zero conditional: always true" },
    ],
  },

  // ─── Passive Voice ────────────────────────────────────────────────────────
  {
    id: "g-passive",
    title_he: "גוף סביל",
    title_en: "Passive Voice",
    icon: "↩️",
    description_he: "המשפט הסביל — is/are/was/were + V3",
    color: "from-gray-500 to-slate-700",
    exercises: [
      { id: "g-pass-1", type: "choice", instruction_he: "בחר:", question: "The letter ___ written by Tom.", options: ["is", "was", "are", "be"], correctIndex: 0, explanation_he: "Passive Present יחיד: is + V3" },
      { id: "g-pass-2", type: "fillblank", instruction_he: "השלם:", sentence: "The windows ___ cleaned every week.", options: ["is", "are", "was", "were"], correctIndex: 1, explanation_he: "windows = רבים: are" },
      { id: "g-pass-3", type: "choice", instruction_he: "בחר:", question: "English ___ spoken all over the world.", options: ["is", "are", "was", "were"], correctIndex: 0, explanation_he: "English = יחיד: is spoken" },
      { id: "g-pass-4", type: "fillblank", instruction_he: "השלם:", sentence: "The cake ___ eaten by the children.", options: ["is", "are", "was", "were"], correctIndex: 2, explanation_he: "עבר: was eaten" },
      { id: "g-pass-5", type: "choice", instruction_he: "בחר:", question: "Cars ___ made in factories.", options: ["is", "are", "was", "were"], correctIndex: 1, explanation_he: "cars = רבים הווה: are made" },
      { id: "g-pass-6", type: "fillblank", instruction_he: "השלם:", sentence: "The book was ___ by a famous author.", options: ["write", "writing", "written", "wrote"], correctIndex: 2, explanation_he: "was + written (V3)" },
      { id: "g-pass-7", type: "choice", instruction_he: "בחר:", question: "Flowers ___ sold at the market.", options: ["is", "are", "was", "were"], correctIndex: 1, explanation_he: "flowers = רבים: are" },
      { id: "g-pass-8", type: "fillblank", instruction_he: "השלם:", sentence: "The new school was ___ in 2020.", options: ["build", "building", "built", "builds"], correctIndex: 2, explanation_he: "was + built (V3 של build)" },
      { id: "g-pass-9", type: "choice", instruction_he: "בחר:", question: "The letters ___ sent yesterday.", options: ["is", "are", "was", "were"], correctIndex: 3, explanation_he: "letters = רבים עבר: were" },
      { id: "g-pass-10", type: "fillblank", instruction_he: "השלם:", sentence: "This song is ___ by everyone.", options: ["know", "knew", "known", "knowing"], correctIndex: 2, explanation_he: "is + known (V3)" },
      { id: "g-pass-11", type: "choice", instruction_he: "בחר:", question: "The game ___ played every Sunday.", options: ["is", "are", "was", "were"], correctIndex: 0, explanation_he: "the game = יחיד הווה: is" },
      { id: "g-pass-12", type: "fillblank", instruction_he: "השלם:", sentence: "Lunch is ___ at 12 o'clock.", options: ["serve", "serving", "served", "serves"], correctIndex: 2, explanation_he: "is + served (V3)" },
      { id: "g-pass-13", type: "choice", instruction_he: "בחר:", question: "The dog was ___ by a kind family.", options: ["find", "found", "finding", "finds"], correctIndex: 1, explanation_he: "was + found (V3 של find)" },
      { id: "g-pass-14", type: "fillblank", instruction_he: "השלם:", sentence: "These shoes are ___ in Italy.", options: ["make", "made", "making", "makes"], correctIndex: 1, explanation_he: "are + made (V3)" },
      { id: "g-pass-15", type: "choice", instruction_he: "בחר:", question: "New books ___ added to the library.", options: ["is", "are", "was", "were"], correctIndex: 1, explanation_he: "books = רבים הווה: are" },
    ],
  },

  // ─── Comparatives & Superlatives ─────────────────────────────────────────
  {
    id: "g-compare",
    title_he: "השוואות ועליונות",
    title_en: "Comparatives & Superlatives",
    icon: "📊",
    description_he: "השוואות (bigger than) ועליונות (the biggest)",
    color: "from-cyan-500 to-blue-600",
    exercises: [
      { id: "g-cmp-1",  type: "choice",   instruction_he: "בחר:", question: "A whale is ___ than a dolphin.", options: ["big", "bigger", "biggest", "more big"], correctIndex: 1, explanation_he: "one syllable: add -er" },
      { id: "g-cmp-2",  type: "fillblank", instruction_he: "השלם:", sentence: "Mount Everest is the ___ mountain in the world.", options: ["tall", "taller", "tallest", "more tall"], correctIndex: 2, explanation_he: "superlative: the + tallest" },
      { id: "g-cmp-3",  type: "choice",   instruction_he: "בחר:", question: "Today is ___ than yesterday.", options: ["hot", "hotter", "hottest", "more hot"], correctIndex: 1, explanation_he: "hot → hotter (double consonant)" },
      { id: "g-cmp-4",  type: "fillblank", instruction_he: "השלם:", sentence: "She is ___ student in the class.", options: ["smart", "smarter", "the smartest", "most smart"], correctIndex: 2, explanation_he: "superlative: the smartest" },
      { id: "g-cmp-5",  type: "choice",   instruction_he: "בחר:", question: "This book is more ___ than that one.", options: ["interested", "interesting", "interest", "interests"], correctIndex: 1, explanation_he: "long adjective: more interesting" },
      { id: "g-cmp-6",  type: "fillblank", instruction_he: "השלם:", sentence: "Gold is ___ than silver.", options: ["expensive", "more expensive", "most expensive", "expensiver"], correctIndex: 1, explanation_he: "long adjective: more expensive" },
      { id: "g-cmp-7",  type: "choice",   instruction_he: "בחר:", question: "This is the most ___ movie I have seen.", options: ["excite", "exciting", "excited", "excitement"], correctIndex: 1, explanation_he: "the most exciting" },
      { id: "g-cmp-8",  type: "fillblank", instruction_he: "השלם:", sentence: "My bag is ___ than yours.", options: ["heavy", "heavier", "heaviest", "more heavy"], correctIndex: 1, explanation_he: "y → ier: heavier" },
      { id: "g-cmp-9",  type: "choice",   instruction_he: "בחר:", question: "He runs ___ than his brother.", options: ["fast", "faster", "fastest", "more fast"], correctIndex: 1, explanation_he: "fast → faster" },
      { id: "g-cmp-10", type: "fillblank", instruction_he: "השלם:", sentence: "She is the ___ singer in the group.", options: ["good", "better", "best", "gooder"], correctIndex: 2, explanation_he: "superlative of good = the best" },
      { id: "g-cmp-11", type: "choice",   instruction_he: "בחר:", question: "I feel ___ today than I did yesterday.", options: ["good", "better", "best", "well"], correctIndex: 1, explanation_he: "comparative of good = better" },
      { id: "g-cmp-12", type: "fillblank", instruction_he: "השלם:", sentence: "This is ___ than I expected.", options: ["bad", "worse", "worst", "more bad"], correctIndex: 1, explanation_he: "comparative of bad = worse" },
      { id: "g-cmp-13", type: "choice",   instruction_he: "בחר:", question: "This is the ___ pizza I have ever eaten.", options: ["good", "better", "best", "most good"], correctIndex: 2, explanation_he: "superlative of good = the best" },
      { id: "g-cmp-14", type: "fillblank", instruction_he: "השלם:", sentence: "A cheetah is ___ than a lion.", options: ["fast", "faster", "fastest", "more fast"], correctIndex: 1, explanation_he: "fast → faster" },
      { id: "g-cmp-15", type: "choice",   instruction_he: "בחר:", question: "This exercise is ___ than the last one.", options: ["easy", "easier", "easiest", "more easy"], correctIndex: 1, explanation_he: "y → ier: easier" },
      { id: "g-cmp-16", type: "fillblank", instruction_he: "השלם:", sentence: "She has the ___ hair in the class.", options: ["long", "longer", "longest", "more long"], correctIndex: 2, explanation_he: "superlative: the longest" },
      { id: "g-cmp-17", type: "choice",   instruction_he: "בחר:", question: "My sister is ___ than me.", options: ["young", "younger", "youngest", "more young"], correctIndex: 1, explanation_he: "young → younger" },
      { id: "g-cmp-18", type: "fillblank", instruction_he: "השלם:", sentence: "This is ___ road in the country.", options: ["long", "longer", "the longest", "most long"], correctIndex: 2, explanation_he: "superlative with the" },
      { id: "g-cmp-19", type: "choice",   instruction_he: "בחר:", question: "Dogs are ___ than cats.", options: ["friend", "friendly", "friendlier", "friendliest"], correctIndex: 2, explanation_he: "friendly → friendlier" },
      { id: "g-cmp-20", type: "fillblank", instruction_he: "השלם:", sentence: "This bag is the ___ of all.", options: ["heavy", "heavier", "heaviest", "most heavy"], correctIndex: 2, explanation_he: "superlative: the heaviest" },
    ],
  },

  // ─── Imperatives ─────────────────────────────────────────────────────────
  {
    id: "g-imperative",
    title_he: "פקודות",
    title_en: "Imperatives",
    icon: "👋",
    description_he: "משפטי פקודה — Open the door! Don't run!",
    color: "from-orange-500 to-red-600",
    exercises: [
      { id: "g-imp-1",  type: "choice",   instruction_he: "בחר את הפקודה הנכונה:", question: "You want someone to open the window. You say:", options: ["Open the window!", "Opens the window!", "Opening the window!", "You open the window!"], correctIndex: 0, explanation_he: "פקודה: פועל בסיסי ללא נושא" },
      { id: "g-imp-2",  type: "fillblank", instruction_he: "השלם:", sentence: "___ the door, please.", options: ["Close", "Closes", "Closed", "Closing"], correctIndex: 0, explanation_he: "פקודה: פועל בסיסי" },
      { id: "g-imp-3",  type: "choice",   instruction_he: "בחר:", question: "You want someone to stop making noise:", options: ["Be quiet!", "Are quiet!", "Being quiet!", "You be quiet!"], correctIndex: 0, explanation_he: "Be + adjective בפקודה" },
      { id: "g-imp-4",  type: "fillblank", instruction_he: "השלם:", sentence: "Don't ___ in class!", options: ["run", "runs", "running", "ran"], correctIndex: 0, explanation_he: "שלילה בפקודה: Don't + פועל בסיסי" },
      { id: "g-imp-5",  type: "choice",   instruction_he: "בחר:", question: "How do you tell someone NOT to eat in class?", options: ["Don't eat in class!", "Doesn't eat in class!", "Not eat in class!", "No eating in class please"], correctIndex: 0, explanation_he: "שלילה: Don't + infinitive" },
      { id: "g-imp-6",  type: "fillblank", instruction_he: "השלם:", sentence: "Please ___ your hands before eating.", options: ["wash", "washing", "washes", "washed"], correctIndex: 0, explanation_he: "פקודה מנומסת: please + verb" },
      { id: "g-imp-7",  type: "choice",   instruction_he: "בחר:", question: "The teacher says: '___ page ten, please.'", options: ["Open", "Opens", "Opening", "Opened"], correctIndex: 0, explanation_he: "Open = פקודה" },
      { id: "g-imp-8",  type: "fillblank", instruction_he: "השלם:", sentence: "Don't ___ your phone in class.", options: ["use", "using", "used", "uses"], correctIndex: 0, explanation_he: "Don't + verb base" },
      { id: "g-imp-9",  type: "choice",   instruction_he: "בחר:", question: "Which sentence is a negative imperative?", options: ["Don't touch that!", "He doesn't touch it.", "You aren't touching it.", "She is not touching."], correctIndex: 0, explanation_he: "Don't + verb = שלילת פקודה" },
      { id: "g-imp-10", type: "fillblank", instruction_he: "השלם:", sentence: "Always ___ kind to others.", options: ["be", "are", "is", "being"], correctIndex: 0, explanation_he: "Always + be (פקודה כללית)" },
    ],
  },

  // ─── Articles (a / an / the) ──────────────────────────────────────────────
  {
    id: "g-articles",
    title_he: "כתיב (Articles): a, an, the",
    title_en: "Articles: a / an / the",
    icon: "📰",
    description_he: "מתי משתמשים ב-a, an, ו-the",
    color: "from-blue-500 to-indigo-600",
    exercises: [
      { id: "g-art-1", type: "choice", instruction_he: "בחר:", question: "I have ___ dog.", options: ["a", "an", "the", "-"], correctIndex: 0, explanation_he: "dog מתחיל בעיצור: a dog" },
      { id: "g-art-2", type: "fillblank", instruction_he: "השלם:", sentence: "She is ___ honest person.", options: ["a", "an", "the", "-"], correctIndex: 1, explanation_he: "honest מתחיל בתנועה (h שקט): an honest" },
      { id: "g-art-3", type: "choice", instruction_he: "בחר:", question: "___ sun rises in the east.", options: ["A", "An", "The", "-"], correctIndex: 2, explanation_he: "ידוע ויחיד: the sun" },
      { id: "g-art-4", type: "fillblank", instruction_he: "השלם:", sentence: "She plays ___ piano.", options: ["a", "an", "the", "-"], correctIndex: 2, explanation_he: "כלי נגינה: the piano" },
      { id: "g-art-5", type: "choice", instruction_he: "בחר:", question: "We went to ___ park yesterday.", options: ["a", "an", "the", "-"], correctIndex: 2, explanation_he: "פארק ספציפי שכבר יודעים עליו: the park" },
      { id: "g-art-6", type: "fillblank", instruction_he: "השלם:", sentence: "I saw ___ elephant at the zoo.", options: ["a", "an", "the", "-"], correctIndex: 1, explanation_he: "elephant מתחיל בתנועה: an elephant" },
      { id: "g-art-7", type: "choice", instruction_he: "בחר:", question: "He is ___ best student in the class.", options: ["a", "an", "the", "-"], correctIndex: 2, explanation_he: "עם עליון (best): the best" },
      { id: "g-art-8", type: "fillblank", instruction_he: "השלם:", sentence: "I drink ___ milk every day.", options: ["a", "an", "the", "-"], correctIndex: 3, explanation_he: "חומר כללי (milk בכלל): ללא כתיב" },
      { id: "g-art-9", type: "choice", instruction_he: "בחר:", question: "Open ___ window, please.", options: ["a", "an", "the", "-"], correctIndex: 2, explanation_he: "חלון ספציפי שרואים: the window" },
      { id: "g-art-10", type: "fillblank", instruction_he: "השלם:", sentence: "She is ___ teacher.", options: ["a", "an", "the", "-"], correctIndex: 0, explanation_he: "מקצוע: a teacher" },
      { id: "g-art-11", type: "choice", instruction_he: "בחר:", question: "He bought ___ orange at the market.", options: ["a", "an", "the", "-"], correctIndex: 1, explanation_he: "orange מתחיל בתנועה: an orange" },
      { id: "g-art-12", type: "fillblank", instruction_he: "השלם:", sentence: "___ Nile is a famous river.", options: ["A", "An", "The", "-"], correctIndex: 2, explanation_he: "שמות נהרות: the Nile" },
      { id: "g-art-13", type: "choice", instruction_he: "בחר:", question: "I need ___ umbrella. It is raining.", options: ["a", "an", "the", "-"], correctIndex: 1, explanation_he: "umbrella מתחיל בתנועה (u): an umbrella" },
      { id: "g-art-14", type: "fillblank", instruction_he: "השלם:", sentence: "___ children love ice cream.", options: ["A", "An", "The", "-"], correctIndex: 3, explanation_he: "ילדים בכלל (כללי): ללא כתיב" },
      { id: "g-art-15", type: "choice", instruction_he: "בחר:", question: "I saw ___ cat. ___ cat was black.", options: ["a / The", "the / A", "a / A", "the / The"], correctIndex: 0, explanation_he: "הזכרה ראשונה: a; הזכרה שנייה: the" },
    ],
  },

  // ─── Plurals (irregular) ──────────────────────────────────────────────────
  {
    id: "g-plurals",
    title_he: "רבים לא-רגולריים",
    title_en: "Irregular Plurals",
    icon: "👥",
    description_he: "child→children, tooth→teeth, foot→feet ועוד",
    color: "from-emerald-400 to-green-600",
    exercises: [
      { id: "g-plur-1", type: "choice", instruction_he: "מה הרבים של child?", question: "There are ten ___ in the park.", options: ["childs", "childes", "children", "childrens"], correctIndex: 2, explanation_he: "child → children (לא רגולרי)" },
      { id: "g-plur-2", type: "fillblank", instruction_he: "השלם:", sentence: "I brush my ___ every morning.", options: ["tooths", "teeth", "teeths", "toothes"], correctIndex: 1, explanation_he: "tooth → teeth" },
      { id: "g-plur-3", type: "choice", instruction_he: "מה הרבים של foot?", question: "Her ___ are cold.", options: ["foots", "feets", "feet", "footies"], correctIndex: 2, explanation_he: "foot → feet" },
      { id: "g-plur-4", type: "fillblank", instruction_he: "השלם:", sentence: "The ___ ate the cheese.", options: ["mouses", "mouse", "mice", "mices"], correctIndex: 2, explanation_he: "mouse → mice" },
      { id: "g-plur-5", type: "choice", instruction_he: "מה הרבים של person?", question: "There are five ___ in the room.", options: ["persons", "peoples", "people", "persones"], correctIndex: 2, explanation_he: "person → people (לא רגולרי)" },
      { id: "g-plur-6", type: "fillblank", instruction_he: "השלם:", sentence: "The ___ are shopping at the market.", options: ["womans", "womens", "woman", "women"], correctIndex: 3, explanation_he: "woman → women" },
      { id: "g-plur-7", type: "choice", instruction_he: "מה הרבים של man?", question: "Two ___ are waiting outside.", options: ["mans", "manes", "men", "mens"], correctIndex: 2, explanation_he: "man → men" },
      { id: "g-plur-8", type: "fillblank", instruction_he: "השלם:", sentence: "The ___ are swimming in the pond.", options: ["gooses", "geese", "geeses", "goose"], correctIndex: 1, explanation_he: "goose → geese" },
      { id: "g-plur-9", type: "choice", instruction_he: "בחר:", question: "My ___ hurt after walking all day.", options: ["foots", "foot", "feets", "feet"], correctIndex: 3, explanation_he: "foot → feet" },
      { id: "g-plur-10", type: "choice", instruction_he: "בחר:", question: "The ___ are playing in the yard.", options: ["childs", "childrens", "children", "child"], correctIndex: 2, explanation_he: "children = רבים של child" },
      { id: "g-plur-11", type: "fillblank", instruction_he: "השלם:", sentence: "These ___ are very sharp.", options: ["knifes", "knives", "knifes", "knife"], correctIndex: 1, explanation_he: "knife → knives (f → ves)" },
      { id: "g-plur-12", type: "choice", instruction_he: "מה הרבים של leaf?", question: "The ___ fall in autumn.", options: ["leafs", "leaves", "leafes", "leaf"], correctIndex: 1, explanation_he: "leaf → leaves (f → ves)" },
      { id: "g-plur-13", type: "fillblank", instruction_he: "השלם:", sentence: "Several ___ were seen in the forest.", options: ["deers", "deeres", "deer", "dears"], correctIndex: 2, explanation_he: "deer → deer (ללא שינוי)" },
      { id: "g-plur-14", type: "choice", instruction_he: "בחר:", question: "The ___ are white and fluffy.", options: ["sheeps", "sheep", "sheepes", "sheepies"], correctIndex: 1, explanation_he: "sheep → sheep (ללא שינוי)" },
      { id: "g-plur-15", type: "fillblank", instruction_he: "השלם:", sentence: "We saw many ___ at the aquarium.", options: ["fishs", "fishes", "fish", "fishies"], correctIndex: 2, explanation_he: "fish → fish (כשמדברים על אותו מין)" },
    ],
  },

  // ─── Object Pronouns & Possessives ───────────────────────────────────────
  {
    id: "g-pronouns-adv",
    title_he: "כינויי מושא ושייכות",
    title_en: "Object Pronouns & Possessives",
    icon: "🙋",
    description_he: "me/him/her/us/them — mine/yours/his/hers",
    color: "from-violet-400 to-purple-600",
    exercises: [
      { id: "g-proa-1", type: "choice", instruction_he: "בחר:", question: "She gave ___ a present. (לי)", options: ["I", "me", "my", "mine"], correctIndex: 1, explanation_he: "כינוי מושא: me" },
      { id: "g-proa-2", type: "fillblank", instruction_he: "השלם:", sentence: "This book is ___. (שלי)", options: ["my", "me", "mine", "I"], correctIndex: 2, explanation_he: "כינוי שייכות עצמאי: mine" },
      { id: "g-proa-3", type: "choice", instruction_he: "בחר:", question: "Can you help ___? (אותו)", options: ["he", "his", "him", "himself"], correctIndex: 2, explanation_he: "כינוי מושא זכר: him" },
      { id: "g-proa-4", type: "fillblank", instruction_he: "השלם:", sentence: "That red bag is ___. (שלה)", options: ["her", "hers", "she", "herself"], correctIndex: 1, explanation_he: "כינוי שייכות עצמאי נקבה: hers" },
      { id: "g-proa-5", type: "choice", instruction_he: "בחר:", question: "I called ___ yesterday. (אותה)", options: ["she", "her", "hers", "herself"], correctIndex: 1, explanation_he: "כינוי מושא נקבה: her" },
      { id: "g-proa-6", type: "fillblank", instruction_he: "השלם:", sentence: "These shoes are ___. (שלך)", options: ["your", "you", "yours", "yourself"], correctIndex: 2, explanation_he: "כינוי שייכות עצמאי: yours" },
      { id: "g-proa-7", type: "choice", instruction_he: "בחר:", question: "The teacher told ___ to be quiet. (אותנו)", options: ["we", "our", "ours", "us"], correctIndex: 3, explanation_he: "כינוי מושא רבים ראשון: us" },
      { id: "g-proa-8", type: "fillblank", instruction_he: "השלם:", sentence: "The dog is ___ — we found it. (שלנו)", options: ["our", "us", "ours", "we"], correctIndex: 2, explanation_he: "כינוי שייכות עצמאי: ours" },
      { id: "g-proa-9", type: "choice", instruction_he: "בחר:", question: "She saw ___ at the mall. (אותם)", options: ["they", "their", "theirs", "them"], correctIndex: 3, explanation_he: "כינוי מושא רבים: them" },
      { id: "g-proa-10", type: "fillblank", instruction_he: "השלם:", sentence: "This car is ___. (שלהם)", options: ["their", "they", "theirs", "them"], correctIndex: 2, explanation_he: "כינוי שייכות עצמאי: theirs" },
      { id: "g-proa-11", type: "choice", instruction_he: "בחר:", question: "Is this your pen? — Yes, it's ___.", options: ["my", "me", "mine", "I"], correctIndex: 2, explanation_he: "mine = שלי (עצמאי)" },
      { id: "g-proa-12", type: "fillblank", instruction_he: "השלם:", sentence: "He told ___ the secret. (לה)", options: ["she", "her", "hers", "herself"], correctIndex: 1, explanation_he: "כינוי מושא: her" },
      { id: "g-proa-13", type: "choice", instruction_he: "בחר:", question: "Is that your bag? — No, it's ___. (שלו)", options: ["he", "him", "his", "himself"], correctIndex: 2, explanation_he: "his = שלו (גם כינוי שייכות עצמאי)" },
      { id: "g-proa-14", type: "fillblank", instruction_he: "השלם:", sentence: "Please send ___ the photo. (לנו)", options: ["we", "our", "ours", "us"], correctIndex: 3, explanation_he: "כינוי מושא: us" },
      { id: "g-proa-15", type: "choice", instruction_he: "בחר:", question: "I like ___ new house. (שלהם)", options: ["they", "them", "their", "theirs"], correctIndex: 2, explanation_he: "לפני שם עצם: their (כינוי שייכות)" },
    ],
  },

  // ─── Prepositions of Time ─────────────────────────────────────────────────
  {
    id: "g-prepositions-time",
    title_he: "מילות יחס — זמן",
    title_en: "Prepositions of Time: in / on / at",
    icon: "⏰",
    description_he: "in the morning, on Monday, at 3 o'clock",
    color: "from-amber-400 to-orange-500",
    exercises: [
      { id: "g-prep-1", type: "choice", instruction_he: "בחר:", question: "I wake up ___ 7 o'clock.", options: ["in", "on", "at", "by"], correctIndex: 2, explanation_he: "at + שעה מדויקת" },
      { id: "g-prep-2", type: "fillblank", instruction_he: "השלם:", sentence: "The concert starts ___ Friday.", options: ["in", "on", "at", "by"], correctIndex: 1, explanation_he: "on + יום בשבוע" },
      { id: "g-prep-3", type: "choice", instruction_he: "בחר:", question: "She was born ___ 2015.", options: ["in", "on", "at", "by"], correctIndex: 0, explanation_he: "in + שנה" },
      { id: "g-prep-4", type: "fillblank", instruction_he: "השלם:", sentence: "We eat dinner ___ the evening.", options: ["in", "on", "at", "by"], correctIndex: 0, explanation_he: "in + חלק של היום (in the morning/evening)" },
      { id: "g-prep-5", type: "choice", instruction_he: "בחר:", question: "The exam is ___ Monday morning.", options: ["in", "on", "at", "by"], correctIndex: 1, explanation_he: "on + יום: on Monday morning" },
      { id: "g-prep-6", type: "fillblank", instruction_he: "השלם:", sentence: "I have lived here ___ 2020.", options: ["for", "since", "ago", "during"], correctIndex: 1, explanation_he: "since = מאז נקודת זמן: since 2020" },
      { id: "g-prep-7", type: "choice", instruction_he: "בחר:", question: "She has studied English ___ five years.", options: ["for", "since", "ago", "during"], correctIndex: 0, explanation_he: "for + משך זמן: for five years" },
      { id: "g-prep-8", type: "fillblank", instruction_he: "השלם:", sentence: "I met him three years ___.", options: ["for", "since", "ago", "during"], correctIndex: 2, explanation_he: "ago = לפני: three years ago" },
      { id: "g-prep-9", type: "choice", instruction_he: "בחר:", question: "___ the summer, we go swimming.", options: ["For", "Since", "Ago", "During"], correctIndex: 3, explanation_he: "during = במהלך תקופה" },
      { id: "g-prep-10", type: "fillblank", instruction_he: "השלם:", sentence: "The train arrives ___ midnight.", options: ["in", "on", "at", "by"], correctIndex: 2, explanation_he: "at midnight, at noon — at + זמן מיוחד" },
      { id: "g-prep-11", type: "choice", instruction_he: "בחר:", question: "My birthday is ___ July.", options: ["in", "on", "at", "by"], correctIndex: 0, explanation_he: "in + חודש" },
      { id: "g-prep-12", type: "fillblank", instruction_he: "השלם:", sentence: "We have a test ___ the 15th of March.", options: ["in", "on", "at", "by"], correctIndex: 1, explanation_he: "on + תאריך ספציפי" },
      { id: "g-prep-13", type: "choice", instruction_he: "בחר:", question: "She calls me ___ night.", options: ["in", "on", "at", "by"], correctIndex: 2, explanation_he: "at night" },
      { id: "g-prep-14", type: "fillblank", instruction_he: "השלם:", sentence: "He has been sick ___ last Monday.", options: ["for", "since", "ago", "during"], correctIndex: 1, explanation_he: "since = מאז: since last Monday" },
      { id: "g-prep-15", type: "choice", instruction_he: "בחר:", question: "I usually study ___ the afternoon.", options: ["in", "on", "at", "by"], correctIndex: 0, explanation_he: "in the afternoon" },
    ],
  },

  // ─── Questions with WH- words ─────────────────────────────────────────────
  {
    id: "g-wh-questions",
    title_he: "שאלות WH",
    title_en: "WH- Questions",
    icon: "❓",
    description_he: "Who, What, Where, When, Why, How",
    color: "from-sky-400 to-blue-500",
    exercises: [
      { id: "g-whq-1", type: "choice", instruction_he: "בחר:", question: "___ did you go yesterday?", options: ["What", "Where", "When", "Why"], correctIndex: 1, explanation_he: "Where = איפה / לאן (מקום)" },
      { id: "g-whq-2", type: "fillblank", instruction_he: "השלם:", sentence: "___ did she say?", options: ["What", "Where", "When", "Who"], correctIndex: 0, explanation_he: "What = מה" },
      { id: "g-whq-3", type: "choice", instruction_he: "בחר:", question: "___ does this cost?", options: ["How many", "How much", "How long", "How often"], correctIndex: 1, explanation_he: "How much = כמה (לא נספר)" },
      { id: "g-whq-4", type: "fillblank", instruction_he: "השלם:", sentence: "___ books do you have?", options: ["How much", "How many", "How long", "How often"], correctIndex: 1, explanation_he: "How many + נספר (books)" },
      { id: "g-whq-5", type: "choice", instruction_he: "בחר:", question: "___ did the party start?", options: ["What", "Where", "When", "Why"], correctIndex: 2, explanation_he: "When = מתי" },
      { id: "g-whq-6", type: "fillblank", instruction_he: "השלם:", sentence: "___ is your teacher? (מי)", options: ["What", "Where", "Who", "Whose"], correctIndex: 2, explanation_he: "Who = מי" },
      { id: "g-whq-7", type: "choice", instruction_he: "בחר:", question: "___ are you crying?", options: ["What", "Where", "When", "Why"], correctIndex: 3, explanation_he: "Why = למה" },
      { id: "g-whq-8", type: "fillblank", instruction_he: "השלם:", sentence: "___ did you come to school today? (כיצד)", options: ["What", "How", "Why", "Where"], correctIndex: 1, explanation_he: "How = כיצד / איך" },
      { id: "g-whq-9", type: "choice", instruction_he: "בחר:", question: "___ pen is this?", options: ["Who", "Whose", "Which", "What"], correctIndex: 1, explanation_he: "Whose = של מי" },
      { id: "g-whq-10", type: "fillblank", instruction_he: "השלם:", sentence: "___ color do you prefer?", options: ["Who", "Whose", "Which", "What"], correctIndex: 2, explanation_he: "Which = איזה (מבין אפשרויות)" },
      { id: "g-whq-11", type: "choice", instruction_he: "בחר:", question: "___ long is the film?", options: ["How", "What", "Which", "When"], correctIndex: 0, explanation_he: "How long = כמה זמן / כמה ארוך" },
      { id: "g-whq-12", type: "fillblank", instruction_he: "השלם:", sentence: "___ often do you exercise?", options: ["What", "How", "Which", "When"], correctIndex: 1, explanation_he: "How often = כמה פעמים" },
      { id: "g-whq-13", type: "choice", instruction_he: "בחר:", question: "___ is your favourite sport?", options: ["Where", "Who", "What", "Whose"], correctIndex: 2, explanation_he: "What = מה (שאל על דבר)" },
      { id: "g-whq-14", type: "fillblank", instruction_he: "השלם:", sentence: "___ did they arrive?", options: ["Where", "When", "Why", "Who"], correctIndex: 1, explanation_he: "When = מתי" },
      { id: "g-whq-15", type: "choice", instruction_he: "בחר:", question: "___ far is it to the school?", options: ["What", "How", "Which", "Whose"], correctIndex: 1, explanation_he: "How far = כמה רחוק" },
    ],
  },

  // ─── Adjective Order ─────────────────────────────────────────────────────
  {
    id: "g-adjective-order",
    title_he: "סדר שמות תואר",
    title_en: "Adjective Order",
    icon: "🎨",
    description_he: "גודל לפני צבע: a big red ball",
    color: "from-rose-400 to-pink-600",
    exercises: [
      { id: "g-adj-1", type: "choice", instruction_he: "בחר את הסדר הנכון:", question: "She carries a ___ bag.", options: ["red small", "small red", "red little", "little-red"], correctIndex: 1, explanation_he: "גודל לפני צבע: small red bag" },
      { id: "g-adj-2", type: "fillblank", instruction_he: "השלם:", sentence: "He has ___ eyes.", options: ["blue beautiful big", "big beautiful blue", "beautiful big blue", "beautiful blue big"], correctIndex: 2, explanation_he: "דעה → גודל → צבע: beautiful big blue" },
      { id: "g-adj-3", type: "choice", instruction_he: "בחר:", question: "They live in a ___ house.", options: ["old white big", "big old white", "white big old", "big white old"], correctIndex: 1, explanation_he: "גודל → גיל → צבע: big old white" },
      { id: "g-adj-4", type: "fillblank", instruction_he: "השלם:", sentence: "I bought a ___ car.", options: ["red new small", "small new red", "new small red", "small red new"], correctIndex: 1, explanation_he: "גודל → גיל → צבע: small new red" },
      { id: "g-adj-5", type: "choice", instruction_he: "בחר:", question: "She wore a ___ dress.", options: ["long beautiful blue", "beautiful long blue", "blue long beautiful", "beautiful blue long"], correctIndex: 1, explanation_he: "דעה → גודל/אורך → צבע" },
      { id: "g-adj-6", type: "fillblank", instruction_he: "השלם:", sentence: "It is a ___ day.", options: ["sunny lovely warm", "lovely warm sunny", "warm lovely sunny", "sunny warm lovely"], correctIndex: 1, explanation_he: "דעה לפני מזג אוויר: lovely warm sunny" },
      { id: "g-adj-7", type: "choice", instruction_he: "בחר:", question: "The dog is ___.", options: ["big and black friendly", "friendly, big, black", "black big friendly", "big friendly black"], correctIndex: 1, explanation_he: "דעה → גודל → צבע: friendly, big, black" },
      { id: "g-adj-8", type: "fillblank", instruction_he: "השלם:", sentence: "She has ___ hair.", options: ["black long beautiful", "long beautiful black", "beautiful long black", "beautiful black long"], correctIndex: 2, explanation_he: "דעה → אורך → צבע: beautiful long black" },
      { id: "g-adj-9", type: "choice", instruction_he: "בחר:", question: "He gave me a ___ ring.", options: ["gold small round", "round small gold", "small round gold", "gold round small"], correctIndex: 2, explanation_he: "צורה → גודל → חומר: small round gold" },
      { id: "g-adj-10", type: "fillblank", instruction_he: "השלם:", sentence: "They saw an ___ bird.", options: ["amazing old small", "small old amazing", "amazing small old", "old amazing small"], correctIndex: 2, explanation_he: "דעה → גודל → גיל: amazing small old" },
    ],
  },

  // ─── Modal Verbs: Can / Could / May ───────────────────────────────────────
  {
    id: "g-modals",
    title_he: "פעלי עזר: can / could / may",
    title_en: "Modal Verbs: can / could / may",
    icon: "🔑",
    description_he: "יכולת, רשות ובקשה מנומסת",
    color: "from-teal-500 to-green-600",
    exercises: [
      { id: "g-mod-1", type: "choice", instruction_he: "בחר:", question: "___ I borrow your pen?", options: ["Can", "Could", "Both are correct", "Neither"], correctIndex: 2, explanation_he: "Can I / Could I — שניהם מנומסים; could = יותר מנומס" },
      { id: "g-mod-2", type: "fillblank", instruction_he: "השלם:", sentence: "She ___ swim when she was five.", options: ["can", "could", "may", "might"], correctIndex: 1, explanation_he: "could = יכולת בעבר" },
      { id: "g-mod-3", type: "choice", instruction_he: "בחר:", question: "___ you please help me?", options: ["Can", "Could", "May", "Might"], correctIndex: 1, explanation_he: "Could you please...? = בקשה מנומסת מאוד" },
      { id: "g-mod-4", type: "fillblank", instruction_he: "השלם:", sentence: "___ I use the bathroom?", options: ["Can", "Could", "May", "All correct"], correctIndex: 3, explanation_he: "Can / Could / May I...? — כולם מנומסים לבקשת רשות" },
      { id: "g-mod-5", type: "choice", instruction_he: "בחר:", question: "He ___ run very fast as a child.", options: ["can", "could", "may", "might"], correctIndex: 1, explanation_he: "could = יכולת בעבר" },
      { id: "g-mod-6", type: "fillblank", instruction_he: "השלם:", sentence: "You ___ not enter without a ticket.", options: ["can", "may", "could", "might"], correctIndex: 1, explanation_he: "may not = אין רשות" },
      { id: "g-mod-7", type: "choice", instruction_he: "בחר:", question: "___ you open the door for me?", options: ["May", "Could", "Might", "Should"], correctIndex: 1, explanation_he: "Could you...? = בקשה מנומסת" },
      { id: "g-mod-8", type: "fillblank", instruction_he: "השלם:", sentence: "I ___ not sleep last night.", options: ["can", "could", "may", "might"], correctIndex: 1, explanation_he: "could not = לא יכולתי (בעבר)" },
      { id: "g-mod-9", type: "choice", instruction_he: "בחר:", question: "Fish ___ breathe underwater.", options: ["could", "may", "can", "might"], correctIndex: 2, explanation_he: "can = יכולת עובדתית (הווה)" },
      { id: "g-mod-10", type: "fillblank", instruction_he: "השלם:", sentence: "When I was young, I ___ speak French.", options: ["can", "could", "may", "might"], correctIndex: 1, explanation_he: "could = יכולת בעבר" },
      { id: "g-mod-11", type: "choice", instruction_he: "בחר:", question: "You ___ go home now. (רשות)", options: ["may", "can", "could", "All correct"], correctIndex: 3, explanation_he: "may / can / could — כולם נכונים לרשות" },
      { id: "g-mod-12", type: "fillblank", instruction_he: "השלם:", sentence: "___ you pass me the salt, please?", options: ["May", "Could", "Might", "Should"], correctIndex: 1, explanation_he: "Could you...? = בקשה מנומסת" },
      { id: "g-mod-13", type: "choice", instruction_he: "בחר:", question: "She ___ not play tennis before, but she learned.", options: ["can", "could", "may", "might"], correctIndex: 1, explanation_he: "could not = לא יכלה בעבר" },
      { id: "g-mod-14", type: "fillblank", instruction_he: "השלם:", sentence: "He ___ ride a bike now — he practised all summer.", options: ["can", "could", "may", "should"], correctIndex: 0, explanation_he: "can = יכולת בהווה" },
      { id: "g-mod-15", type: "choice", instruction_he: "בחר:", question: "___ I sit here?", options: ["Could", "May", "Can", "All correct"], correctIndex: 3, explanation_he: "Could / May / Can — כולם מנומסים" },
    ],
  },

  // ─── Should / Must / Have to ──────────────────────────────────────────────
  {
    id: "g-obligation",
    title_he: "חובה: should / must / have to",
    title_en: "Obligation: should / must / have to",
    icon: "📋",
    description_he: "עצה, חובה, ועצה חזקה",
    color: "from-red-500 to-orange-600",
    exercises: [
      { id: "g-obl-1", type: "choice", instruction_he: "בחר:", question: "You ___ brush your teeth every day.", options: ["should", "must", "have to", "All correct"], correctIndex: 3, explanation_he: "should (עצה) / must / have to — כולם מתאימים להרגל בריאות" },
      { id: "g-obl-2", type: "fillblank", instruction_he: "השלם:", sentence: "You ___ wear a seatbelt. It is the law.", options: ["should", "must", "might", "could"], correctIndex: 1, explanation_he: "must = חובה חזקה / חוק" },
      { id: "g-obl-3", type: "choice", instruction_he: "בחר:", question: "She ___ study more — her grades are low.", options: ["must", "should", "have to", "might"], correctIndex: 1, explanation_he: "should = עצה" },
      { id: "g-obl-4", type: "fillblank", instruction_he: "השלם:", sentence: "I ___ go to school every day.", options: ["should", "must", "have to", "might"], correctIndex: 2, explanation_he: "have to = חובה חיצונית (חוק, כלל)" },
      { id: "g-obl-5", type: "choice", instruction_he: "בחר:", question: "You ___ not run in the hospital.", options: ["should", "must", "have to", "might"], correctIndex: 1, explanation_he: "must not = אסור (חזק)" },
      { id: "g-obl-6", type: "fillblank", instruction_he: "השלם:", sentence: "You ___ eat more vegetables. It is good for you.", options: ["must not", "should", "have to not", "might"], correctIndex: 1, explanation_he: "should = עצה ידידותית" },
      { id: "g-obl-7", type: "choice", instruction_he: "בחר:", question: "She ___ not talk in the library.", options: ["should", "must", "have to", "might"], correctIndex: 0, explanation_he: "should not = לא כדאי (עצה)" },
      { id: "g-obl-8", type: "fillblank", instruction_he: "השלם:", sentence: "He doesn't ___ wear a uniform at this school.", options: ["should", "must", "have to", "might"], correctIndex: 2, explanation_he: "have to = חובה (שלילה: don't have to = אין חובה)" },
      { id: "g-obl-9", type: "choice", instruction_he: "בחר:", question: "I ___ call my grandmother — it has been a long time.", options: ["should", "must not", "don't have to", "might not"], correctIndex: 0, explanation_he: "should = עצה / מחויבות מוסרית" },
      { id: "g-obl-10", type: "fillblank", instruction_he: "השלם:", sentence: "You ___ not eat in class.", options: ["should", "must", "have to", "might"], correctIndex: 1, explanation_he: "must not = אסור (כלל בית ספרי)" },
      { id: "g-obl-11", type: "choice", instruction_he: "בחר:", question: "You don't ___ come if you are sick.", options: ["should", "must", "have to", "might"], correctIndex: 2, explanation_he: "don't have to = אין חובה (לא must not)" },
      { id: "g-obl-12", type: "fillblank", instruction_he: "השלם:", sentence: "Students ___ listen to the teacher.", options: ["should", "must", "have to", "All correct"], correctIndex: 3, explanation_he: "כולם מתאימים (should = עצה, must/have to = חובה)" },
      { id: "g-obl-13", type: "choice", instruction_he: "בחר:", question: "It is free — you ___ not pay.", options: ["should", "must", "have to", "don't have to"], correctIndex: 3, explanation_he: "don't have to = אין צורך" },
      { id: "g-obl-14", type: "fillblank", instruction_he: "השלם:", sentence: "She ___ practice more if she wants to win.", options: ["should", "must", "have to", "might"], correctIndex: 0, explanation_he: "should = עצה / המלצה" },
      { id: "g-obl-15", type: "choice", instruction_he: "בחר:", question: "You ___ not cross a red light.", options: ["should", "must", "don't have to", "might"], correctIndex: 1, explanation_he: "must not = אסור בהחלט" },
    ],
  },
];

export function getGrammarTopicById(id: string): GrammarTopic | undefined {
  return GRAMMAR_TOPICS.find((t) => t.id === id);
}
