import type { Lesson } from "./types";

export const LESSONS: Lesson[] = [
  {
    id: "lesson-01",
    title_he: "בבית הספר",
    subtitle_he: "At School",
    objective_he: "ללמוד מילים על בית הספר",
    icon: "📚",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l1-e1", "l1-e2", "l1-e3", "l1-e4", "l1-e5"],
    vocabularyIds: ["school-01", "school-02", "school-03", "school-04", "school-07", "school-08"],
    estimatedMinutes: 7,
    color: "from-blue-400 to-blue-600",
  },
  {
    id: "lesson-02",
    title_he: "המשפחה שלי",
    subtitle_he: "My Family",
    objective_he: "ללמוד מילים על המשפחה",
    icon: "👨‍👩‍👧",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l2-e1", "l2-e2", "l2-e3", "l2-e4", "l2-e5"],
    vocabularyIds: ["family-01", "family-02", "family-03", "family-04", "family-05", "family-07"],
    estimatedMinutes: 7,
    color: "from-purple-400 to-purple-600",
  },
  {
    id: "lesson-03",
    title_he: "אוכל טעים",
    subtitle_he: "Tasty Food",
    objective_he: "ללמוד מילים על אוכל",
    icon: "🍎",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l3-e1", "l3-e2", "l3-e3", "l3-e4", "l3-e5"],
    vocabularyIds: ["food-01", "food-02", "food-04", "food-06", "food-07", "food-09"],
    estimatedMinutes: 7,
    color: "from-green-400 to-green-600",
  },
  {
    id: "lesson-04",
    title_he: "חיות",
    subtitle_he: "Animals",
    objective_he: "ללמוד מילים על חיות",
    icon: "🐱",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l4-e1", "l4-e2", "l4-e3", "l4-e4", "l4-e5"],
    vocabularyIds: ["animals-01", "animals-02", "animals-03", "animals-04", "animals-05", "animals-08"],
    estimatedMinutes: 7,
    color: "from-yellow-400 to-orange-500",
  },
  {
    id: "lesson-05",
    title_he: "מזג האוויר",
    subtitle_he: "Weather",
    objective_he: "ללמוד מילים על מזג האוויר",
    icon: "☀️",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l5-e1", "l5-e2", "l5-e3", "l5-e4", "l5-e5"],
    vocabularyIds: ["weather-01", "weather-02", "weather-03", "weather-04", "weather-05", "weather-06"],
    estimatedMinutes: 7,
    color: "from-orange-400 to-red-500",
  },
  {
    id: "lesson-06",
    title_he: "הבית שלי",
    subtitle_he: "My Home",
    objective_he: "ללמוד מילים על הבית",
    icon: "🏠",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l6-e1", "l6-e2", "l6-e3", "l6-e4", "l6-e5"],
    vocabularyIds: ["home-01", "home-03", "home-04", "home-05", "home-06", "home-07", "home-08"],
    estimatedMinutes: 7,
    color: "from-teal-400 to-teal-600",
  },
  {
    id: "lesson-07",
    title_he: "מה השעה?",
    subtitle_he: "What Time Is It?",
    objective_he: "ללמוד מילות זמן וימות השבוע",
    icon: "⏰",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l7-e1", "l7-e2", "l7-e3", "l7-e4", "l7-e5"],
    vocabularyIds: ["time-01", "time-02", "time-06", "time-07", "time-08", "time-16"],
    estimatedMinutes: 7,
    color: "from-indigo-400 to-indigo-600",
  },
  {
    id: "lesson-08",
    title_he: "הגוף שלי",
    subtitle_he: "My Body",
    objective_he: "ללמוד חלקי גוף האדם",
    icon: "👁️",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l8-e1", "l8-e2", "l8-e3", "l8-e4", "l8-e5"],
    vocabularyIds: ["body-01", "body-02", "body-03", "body-04", "body-05", "body-08"],
    estimatedMinutes: 7,
    color: "from-rose-400 to-rose-600",
  },
  {
    id: "lesson-09",
    title_he: "הבגדים שלי",
    subtitle_he: "My Clothes",
    objective_he: "ללמוד מילים על ביגוד",
    icon: "👕",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l9-e1", "l9-e2", "l9-e3", "l9-e4", "l9-e5"],
    vocabularyIds: ["clothes-01", "clothes-02", "clothes-05", "clothes-06", "clothes-07", "clothes-08"],
    estimatedMinutes: 7,
    color: "from-pink-400 to-pink-600",
  },
  {
    id: "lesson-10",
    title_he: "צבעים ותיאורים",
    subtitle_he: "Colors & Descriptions",
    objective_he: "ללמוד צבעים ושמות תואר",
    icon: "🌈",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l10-e1", "l10-e2", "l10-e3", "l10-e4", "l10-e5"],
    vocabularyIds: ["colors-01", "colors-02", "colors-03", "colors-04", "adj-01", "adj-02"],
    estimatedMinutes: 7,
    color: "from-fuchsia-400 to-violet-600",
  },
  {
    id: "lesson-11",
    title_he: "העיר שלי",
    subtitle_he: "My City",
    objective_he: "ללמוד מקומות בעיר",
    icon: "🏙️",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l11-e1", "l11-e2", "l11-e3", "l11-e4", "l11-e5"],
    vocabularyIds: ["places-01", "places-04", "places-05", "places-06", "places-08", "places-10"],
    estimatedMinutes: 7,
    color: "from-slate-400 to-slate-600",
  },
  {
    id: "lesson-12",
    title_he: "ספורט ותחביבים",
    subtitle_he: "Sports & Hobbies",
    objective_he: "ללמוד ספורט ופעילויות פנאי",
    icon: "⚽",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l12-e1", "l12-e2", "l12-e3", "l12-e4", "l12-e5"],
    vocabularyIds: ["sport-01", "sport-02", "sport-03", "hobby-01", "hobby-10", "hobby-14"],
    estimatedMinutes: 7,
    color: "from-lime-400 to-green-600",
  },
  {
    id: "lesson-13",
    title_he: "רגשות ותכונות",
    subtitle_he: "Emotions & Traits",
    objective_he: "ללמוד מילים על רגשות ותכונות אישיות",
    icon: "😊",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l13-e1", "l13-e2", "l13-e3", "l13-e4", "l13-e5"],
    vocabularyIds: ["adj-11", "adj-12", "adj-15", "emo-01", "emo-02", "emo-06"],
    estimatedMinutes: 7,
    color: "from-amber-400 to-orange-600",
  },
  {
    id: "lesson-14",
    title_he: "טכנולוגיה",
    subtitle_he: "Technology",
    objective_he: "ללמוד מילים על טכנולוגיה",
    icon: "💻",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l14-e1", "l14-e2", "l14-e3", "l14-e4", "l14-e5"],
    vocabularyIds: ["tech-01", "tech-02", "tech-03", "tech-04", "tech-05", "tech-06"],
    estimatedMinutes: 7,
    color: "from-sky-400 to-blue-700",
  },
  {
    id: "lesson-15",
    title_he: "טבע וסביבה",
    subtitle_he: "Nature & Environment",
    objective_he: "ללמוד מילים על הטבע",
    icon: "🌿",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l15-e1", "l15-e2", "l15-e3", "l15-e4", "l15-e5"],
    vocabularyIds: ["nature-01", "nature-02", "nature-03", "nature-05", "nature-06", "nature-08"],
    estimatedMinutes: 7,
    color: "from-emerald-400 to-green-700",
  },
  {
    id: "lesson-16",
    title_he: "נסיעות וקניות",
    subtitle_he: "Travel & Shopping",
    objective_he: "ללמוד מילים על נסיעות וקניות",
    icon: "✈️",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l16-e1", "l16-e2", "l16-e3", "l16-e4", "l16-e5"],
    vocabularyIds: ["travel-01", "travel-03", "travel-05", "shop-01", "shop-03", "shop-05"],
    estimatedMinutes: 7,
    color: "from-violet-400 to-purple-700",
  },
  {
    id: "lesson-17",
    title_he: "ספורט ופעילות גופנית",
    subtitle_he: "Sports and Exercise",
    objective_he: "ללמוד מילים על ספורט",
    icon: "⚽",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l17-e1", "l17-e2", "l17-e3", "l17-e4", "l17-e5"],
    vocabularyIds: ["sports-01", "sports-02", "sports-03", "sports-04", "sports-05", "sports-06"],
    estimatedMinutes: 7,
    color: "from-emerald-400 to-green-600",
  },
  {
    id: "lesson-18",
    title_he: "עולם הטכנולוגיה",
    subtitle_he: "The World of Technology",
    objective_he: "ללמוד מילים על טכנולוגיה",
    icon: "💻",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l18-e1", "l18-e2", "l18-e3", "l18-e4", "l18-e5"],
    vocabularyIds: ["technology-01", "technology-02", "technology-03", "technology-04", "technology-05", "technology-06"],
    estimatedMinutes: 7,
    color: "from-cyan-400 to-blue-600",
  },
  {
    id: "lesson-19",
    title_he: "רגשות ותחושות",
    subtitle_he: "Feelings and Emotions",
    objective_he: "ללמוד מילים על רגשות",
    icon: "😊",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l19-e1", "l19-e2", "l19-e3", "l19-e4", "l19-e5"],
    vocabularyIds: ["emotions-01", "emotions-02", "emotions-03", "emotions-04", "emotions-05", "emotions-06"],
    estimatedMinutes: 7,
    color: "from-pink-400 to-rose-600",
  },
  {
    id: "lesson-20",
    title_he: "מקצועות ועבודות",
    subtitle_he: "Jobs and Professions",
    objective_he: "ללמוד מילים על מקצועות",
    icon: "👨‍⚕️",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l20-e1", "l20-e2", "l20-e3", "l20-e4", "l20-e5"],
    vocabularyIds: ["professions-01", "professions-02", "professions-03", "professions-04", "professions-05", "professions-06"],
    estimatedMinutes: 7,
    color: "from-violet-400 to-purple-600",
  },
  {
    id: "lesson-21",
    title_he: "נסיעות וחופשה",
    subtitle_he: "Travel and Vacation",
    objective_he: "ללמוד מילים על נסיעות",
    icon: "✈️",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l21-e1", "l21-e2", "l21-e3", "l21-e4", "l21-e5"],
    vocabularyIds: ["travel-01", "travel-02", "travel-03", "travel-04", "travel-05", "travel-06"],
    estimatedMinutes: 7,
    color: "from-sky-400 to-indigo-600",
  },
  {
    id: "lesson-22",
    title_he: "בריאות וגוף",
    subtitle_he: "Health and Body",
    objective_he: "ללמוד מילים על בריאות",
    icon: "🏥",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l22-e1", "l22-e2", "l22-e3", "l22-e4", "l22-e5"],
    vocabularyIds: ["health-01", "health-02", "health-03", "health-04", "health-05", "health-06"],
    estimatedMinutes: 7,
    color: "from-red-400 to-pink-600",
  },
  {
    id: "lesson-23",
    title_he: "קניות ומסחר",
    subtitle_he: "Shopping and Commerce",
    objective_he: "ללמוד מילים על קניות",
    icon: "🛍️",
    skillTargets: ["vocabulary", "reading"],
    exerciseIds: ["l23-e1", "l23-e2", "l23-e3", "l23-e4", "l23-e5"],
    vocabularyIds: ["shopping-01", "shopping-02", "shopping-03", "shopping-04", "shopping-05", "shopping-06"],
    estimatedMinutes: 7,
    color: "from-amber-400 to-orange-600",
  },
  {
    id: "lesson-24",
    title_he: "הטבע סביבנו",
    subtitle_he: "Nature Around Us",
    objective_he: "ללמוד מילים על הטבע",
    icon: "🌿",
    skillTargets: ["vocabulary", "listening"],
    exerciseIds: ["l24-e1", "l24-e2", "l24-e3", "l24-e4", "l24-e5"],
    vocabularyIds: ["nature-01", "nature-02", "nature-03", "nature-04", "nature-05", "nature-06"],
    estimatedMinutes: 7,
    color: "from-lime-400 to-green-600",
  },
];

export function getLessonById(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}

export function getNextLesson(completedIds: string[]): Lesson | undefined {
  return LESSONS.find((l) => !completedIds.includes(l.id));
}
